// This file is auto-generated by @hey-api/openapi-ts

export const EventLocationRequestDTOSchema = {
    type: 'object',
    required: ['name', 'address', 'capacity'],
    properties: {
        name: {
            type: 'string'
        },
        address: {
            type: 'string'
        },
        capacity: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const EventLocationResponseDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        name: {
            type: 'string'
        },
        address: {
            type: 'string'
        },
        capacity: {
            type: 'integer',
            format: 'int32'
        },
        manager: {
            '$ref': '#/components/schemas/UserDTO'
        },
        seats: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/SeatDTO'
            }
        }
    }
} as const;

export const EventLocationResponseDTO1Schema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        name: {
            type: 'string'
        },
        address: {
            type: 'string'
        },
        capacity: {
            type: 'integer',
            format: 'int32'
        },
        manager: {
            '$ref': '#/components/schemas/UserDTO'
        },
        seats: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/SeatDTO'
            }
        }
    }
} as const;

export const EventRequestDTOSchema = {
    type: 'object',
    required: ['name', 'description', 'startTime', 'endTime', 'bookingDeadline', 'eventLocationId'],
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        startTime: {
            '$ref': '#/components/schemas/LocalDateTime'
        },
        endTime: {
            '$ref': '#/components/schemas/LocalDateTime'
        },
        bookingDeadline: {
            '$ref': '#/components/schemas/LocalDateTime'
        },
        eventLocationId: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const EventResponseDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        startTime: {
            '$ref': '#/components/schemas/LocalDateTime'
        },
        endTime: {
            '$ref': '#/components/schemas/LocalDateTime'
        },
        bookingDeadline: {
            '$ref': '#/components/schemas/LocalDateTime'
        },
        location: {
            '$ref': '#/components/schemas/EventLocationResponseDTO'
        },
        manager: {
            '$ref': '#/components/schemas/UserDTO1'
        },
        eventUserAllowances: {
            type: 'array',
            uniqueItems: true,
            items: {
                '$ref': '#/components/schemas/EventUserAllowancesDto'
            }
        }
    }
} as const;

export const EventResponseDTO1Schema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        startTime: {
            '$ref': '#/components/schemas/LocalDateTime'
        },
        endTime: {
            '$ref': '#/components/schemas/LocalDateTime'
        },
        bookingDeadline: {
            '$ref': '#/components/schemas/LocalDateTime'
        },
        location: {
            '$ref': '#/components/schemas/EventLocationResponseDTO1'
        }
    }
} as const;

export const EventUserAllowancesDtoSchema = {
    type: 'object',
    properties: {
        eventId: {
            type: 'integer',
            format: 'int64'
        },
        userId: {
            type: 'integer',
            format: 'int64'
        },
        reservationsAllowedCount: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const LimitedUserDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        username: {
            type: 'string'
        }
    }
} as const;

export const LocalDateTimeSchema = {
    type: 'string',
    format: 'date-time',
    examples: ['2022-03-10T12:15:50']
} as const;

export const LoginRequestDTOSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    }
} as const;

export const ReservationRequestCreateDTOSchema = {
    type: 'object',
    required: ['eventId', 'seatIds'],
    properties: {
        eventId: {
            type: 'integer',
            format: 'int64'
        },
        seatIds: {
            type: 'array',
            items: {
                type: 'integer',
                format: 'int64'
            },
            minItems: 1
        }
    }
} as const;

export const ReservationRequestDTOSchema = {
    type: 'object',
    required: ['eventId', 'userId', 'seatId'],
    properties: {
        eventId: {
            type: 'integer',
            format: 'int64'
        },
        userId: {
            type: 'integer',
            format: 'int64'
        },
        seatId: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const ReservationResponseDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        user: {
            '$ref': '#/components/schemas/UserDTO'
        },
        event: {
            '$ref': '#/components/schemas/EventResponseDTO'
        },
        seat: {
            '$ref': '#/components/schemas/SeatDTO1'
        },
        reservationDateTime: {
            '$ref': '#/components/schemas/LocalDateTime'
        }
    }
} as const;

export const ReservationResponseDTO1Schema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        userId: {
            type: 'integer',
            format: 'int64'
        },
        eventId: {
            type: 'integer',
            format: 'int64'
        },
        seat: {
            '$ref': '#/components/schemas/SeatDTO1'
        },
        reservationDateTime: {
            '$ref': '#/components/schemas/LocalDateTime'
        }
    }
} as const;

export const SeatDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        seatNumber: {
            type: 'string'
        },
        locationId: {
            type: 'integer',
            format: 'int64'
        },
        xCoordinate: {
            type: 'integer',
            format: 'int32'
        },
        yCoordinate: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const SeatDTO1Schema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        seatNumber: {
            type: 'string'
        },
        locationId: {
            type: 'integer',
            format: 'int64'
        },
        xCoordinate: {
            type: 'integer',
            format: 'int32'
        },
        yCoordinate: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const SeatRequestDTOSchema = {
    type: 'object',
    required: ['seatNumber', 'eventLocationId', 'xCoordinate', 'yCoordinate'],
    properties: {
        seatNumber: {
            type: 'string'
        },
        eventLocationId: {
            type: 'integer',
            format: 'int64'
        },
        xCoordinate: {
            type: 'integer',
            format: 'int32'
        },
        yCoordinate: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const SeatResponseDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        seatNumber: {
            type: 'string'
        },
        location: {
            '$ref': '#/components/schemas/EventLocationResponseDTO'
        },
        xCoordinate: {
            type: 'integer',
            format: 'int32'
        },
        yCoordinate: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const UserCreationDTOSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        },
        firstname: {
            type: 'string'
        },
        lastname: {
            type: 'string'
        }
    }
} as const;

export const UserDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        username: {
            type: 'string'
        },
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        email: {
            type: 'string'
        }
    }
} as const;

export const UserDTO1Schema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        username: {
            type: 'string'
        }
    }
} as const;

export const UserProfileUpdateDTOSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        firstname: {
            type: 'string'
        },
        lastname: {
            type: 'string'
        },
        passwordHash: {
            type: 'string'
        },
        roles: {
            type: 'array',
            uniqueItems: true,
            items: {
                type: 'string'
            }
        }
    }
} as const;