// This file is auto-generated by @hey-api/openapi-ts

export type AdminUserUpdateDto = {
    email: string;
    firstname: string;
    lastname: string;
    password?: string;
    roles: string[];
};

export type BlockSeatsRequestDto = {
    eventId?: bigint;
    seatIds?: bigint[];
};

export type DetailedEventResponseDto = {
    id?: bigint;
    name?: string;
    description?: string;
    startTime?: LocalDateTime;
    endTime?: LocalDateTime;
    bookingDeadline?: LocalDateTime;
    location?: EventLocationResponseDto;
    manager?: UserDto;
    eventUserAllowances?: EventUserAllowancesDto[];
};

export type DetailedReservationResponseDto = {
    id?: bigint;
    user?: UserDto;
    event?: DetailedEventResponseDto;
    seat?: SeatDto;
    reservationDateTime?: LocalDateTime;
};

export type EventLocationData = {
    name?: string;
    address?: string;
    capacity?: number;
};

export type EventLocationRegistrationDto = {
    eventLocation?: EventLocationData;
    seats?: SeatData[];
};

export type EventLocationRequestDto = {
    name: string;
    address: string;
    capacity: number;
};

export type EventLocationResponseDto = {
    id?: bigint;
    name?: string;
    address?: string;
    capacity?: number;
    manager?: LimitedUserInfoDto;
    seats?: SeatDto[];
};

export type EventRequestDto = {
    name: string;
    description: string;
    startTime: LocalDateTime;
    endTime: LocalDateTime;
    bookingDeadline: LocalDateTime;
    eventLocationId: bigint;
};

export type EventResponseDto = {
    id?: bigint;
    name?: string;
    description?: string;
    startTime?: LocalDateTime;
    endTime?: LocalDateTime;
    bookingDeadline?: LocalDateTime;
    location?: EventLocationResponseDto;
    reservationsAllowed?: number;
};

export type EventUserAllowancesDto = {
    eventId?: bigint;
    userId?: bigint;
    reservationsAllowedCount?: number;
};

export type LimitedUserInfoDto = {
    id?: bigint;
    username?: string;
};

export type LocalDateTime = Date;

export type LoginRequestDto = {
    username: string;
    password: string;
};

export type ReservationRequestDto = {
    eventId: bigint;
    userId: bigint;
    seatId: bigint;
};

export type ReservationResponseDto = {
    id?: bigint;
    userId?: bigint;
    eventId?: bigint;
    seat?: SeatDto;
    reservationDateTime?: LocalDateTime;
};

export type ReservationStatus = 'RESERVED' | 'BLOCKED';

export const ReservationStatus = {
    RESERVED: 'RESERVED',
    BLOCKED: 'BLOCKED'
} as const;

export type ReservationsRequestCreateDto = {
    eventId: bigint;
    seatIds: bigint[];
};

export type SeatDto = {
    id?: bigint;
    seatNumber?: string;
    locationId?: bigint;
    xCoordinate?: number;
    yCoordinate?: number;
    status?: ReservationStatus;
};

export type SeatData = {
    seatNumber?: string;
    xCoordinate?: number;
    yCoordinate?: number;
};

export type SeatRequestDto = {
    seatNumber: string;
    eventLocationId: bigint;
    xCoordinate: number;
    yCoordinate: number;
};

export type SeatResponseDto = {
    id?: bigint;
    seatNumber?: string;
    location?: EventLocationResponseDto;
    xCoordinate?: number;
    yCoordinate?: number;
    status?: ReservationStatus;
};

export type UserCreationDto = {
    username: string;
    email?: string;
    password: string;
    firstname: string;
    lastname: string;
};

export type UserDto = {
    id?: bigint;
    username?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    emailVerified?: boolean;
    roles?: string[];
};

export type UserProfileUpdateDto = {
    email: string;
    firstname: string;
    lastname: string;
    password: string;
};

export type PostApiAuthLoginData = {
    body: LoginRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiManagerEventlocationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/manager/eventlocations';
};

export type GetApiManagerEventlocationsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiManagerEventlocationsResponses = {
    /**
     * OK
     */
    200: EventLocationResponseDto[];
};

export type GetApiManagerEventlocationsResponse = GetApiManagerEventlocationsResponses[keyof GetApiManagerEventlocationsResponses];

export type PostApiManagerEventlocationsData = {
    body: EventLocationRequestDto;
    path?: never;
    query?: never;
    url: '/api/manager/eventlocations';
};

export type PostApiManagerEventlocationsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiManagerEventlocationsResponses = {
    /**
     * OK
     */
    200: EventLocationResponseDto;
};

export type PostApiManagerEventlocationsResponse = PostApiManagerEventlocationsResponses[keyof PostApiManagerEventlocationsResponses];

export type PostApiManagerEventlocationsRegisterData = {
    body: EventLocationRegistrationDto;
    path?: never;
    query?: never;
    url: '/api/manager/eventlocations/register';
};

export type PostApiManagerEventlocationsRegisterErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiManagerEventlocationsRegisterResponses = {
    /**
     * OK
     */
    200: EventLocationResponseDto;
};

export type PostApiManagerEventlocationsRegisterResponse = PostApiManagerEventlocationsRegisterResponses[keyof PostApiManagerEventlocationsRegisterResponses];

export type DeleteApiManagerEventlocationsByIdData = {
    body?: never;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/manager/eventlocations/{id}';
};

export type DeleteApiManagerEventlocationsByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type DeleteApiManagerEventlocationsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiManagerEventlocationsByIdData = {
    body: EventLocationRequestDto;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/manager/eventlocations/{id}';
};

export type PutApiManagerEventlocationsByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PutApiManagerEventlocationsByIdResponses = {
    /**
     * OK
     */
    200: EventLocationResponseDto;
};

export type PutApiManagerEventlocationsByIdResponse = PutApiManagerEventlocationsByIdResponses[keyof PutApiManagerEventlocationsByIdResponses];

export type GetApiManagerEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/manager/events';
};

export type GetApiManagerEventsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiManagerEventsResponses = {
    /**
     * OK
     */
    200: DetailedEventResponseDto[];
};

export type GetApiManagerEventsResponse = GetApiManagerEventsResponses[keyof GetApiManagerEventsResponses];

export type PostApiManagerEventsData = {
    body: EventRequestDto;
    path?: never;
    query?: never;
    url: '/api/manager/events';
};

export type PostApiManagerEventsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiManagerEventsResponses = {
    /**
     * OK
     */
    200: DetailedEventResponseDto;
};

export type PostApiManagerEventsResponse = PostApiManagerEventsResponses[keyof PostApiManagerEventsResponses];

export type DeleteApiManagerEventsByIdData = {
    body?: never;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/manager/events/{id}';
};

export type DeleteApiManagerEventsByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type DeleteApiManagerEventsByIdResponses = {
    /**
     * Event deleted
     */
    204: void;
};

export type DeleteApiManagerEventsByIdResponse = DeleteApiManagerEventsByIdResponses[keyof DeleteApiManagerEventsByIdResponses];

export type PutApiManagerEventsByIdData = {
    body: EventRequestDto;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/manager/events/{id}';
};

export type PutApiManagerEventsByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PutApiManagerEventsByIdResponses = {
    /**
     * OK
     */
    200: DetailedEventResponseDto;
};

export type PutApiManagerEventsByIdResponse = PutApiManagerEventsByIdResponses[keyof PutApiManagerEventsByIdResponses];

export type GetApiManagerReservationAllowanceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/manager/reservationAllowance';
};

export type GetApiManagerReservationAllowanceErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiManagerReservationAllowanceResponses = {
    /**
     * OK
     */
    200: EventUserAllowancesDto[];
};

export type GetApiManagerReservationAllowanceResponse = GetApiManagerReservationAllowanceResponses[keyof GetApiManagerReservationAllowanceResponses];

export type PostApiManagerReservationAllowanceData = {
    body: EventUserAllowancesDto;
    path?: never;
    query?: never;
    url: '/api/manager/reservationAllowance';
};

export type PostApiManagerReservationAllowanceErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiManagerReservationAllowanceResponses = {
    /**
     * OK
     */
    200: EventUserAllowancesDto;
};

export type PostApiManagerReservationAllowanceResponse = PostApiManagerReservationAllowanceResponses[keyof PostApiManagerReservationAllowanceResponses];

export type GetApiManagerReservationAllowanceEventByEventIdData = {
    body?: never;
    path: {
        eventId: bigint;
    };
    query?: never;
    url: '/api/manager/reservationAllowance/event/{eventId}';
};

export type GetApiManagerReservationAllowanceEventByEventIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiManagerReservationAllowanceEventByEventIdResponses = {
    /**
     * OK
     */
    200: EventUserAllowancesDto[];
};

export type GetApiManagerReservationAllowanceEventByEventIdResponse = GetApiManagerReservationAllowanceEventByEventIdResponses[keyof GetApiManagerReservationAllowanceEventByEventIdResponses];

export type DeleteApiManagerReservationAllowanceByIdData = {
    body?: never;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/manager/reservationAllowance/{id}';
};

export type DeleteApiManagerReservationAllowanceByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type DeleteApiManagerReservationAllowanceByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiManagerReservationAllowanceByIdResponse = DeleteApiManagerReservationAllowanceByIdResponses[keyof DeleteApiManagerReservationAllowanceByIdResponses];

export type GetApiManagerReservationAllowanceByIdData = {
    body?: never;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/manager/reservationAllowance/{id}';
};

export type GetApiManagerReservationAllowanceByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiManagerReservationAllowanceByIdResponses = {
    /**
     * OK
     */
    200: EventUserAllowancesDto;
};

export type GetApiManagerReservationAllowanceByIdResponse = GetApiManagerReservationAllowanceByIdResponses[keyof GetApiManagerReservationAllowanceByIdResponses];

export type GetApiManagerReservationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/manager/reservations';
};

export type GetApiManagerReservationsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiManagerReservationsResponses = {
    /**
     * OK
     */
    200: DetailedReservationResponseDto[];
};

export type GetApiManagerReservationsResponse = GetApiManagerReservationsResponses[keyof GetApiManagerReservationsResponses];

export type PostApiManagerReservationsData = {
    body: ReservationRequestDto;
    path?: never;
    query?: never;
    url: '/api/manager/reservations';
};

export type PostApiManagerReservationsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiManagerReservationsResponses = {
    /**
     * OK
     */
    200: DetailedReservationResponseDto;
};

export type PostApiManagerReservationsResponse = PostApiManagerReservationsResponses[keyof PostApiManagerReservationsResponses];

export type PostApiManagerReservationsBlockData = {
    body: BlockSeatsRequestDto;
    path?: never;
    query?: never;
    url: '/api/manager/reservations/block';
};

export type PostApiManagerReservationsBlockErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiManagerReservationsBlockResponses = {
    /**
     * Seats blocked successfully
     */
    204: void;
};

export type PostApiManagerReservationsBlockResponse = PostApiManagerReservationsBlockResponses[keyof PostApiManagerReservationsBlockResponses];

export type GetApiManagerReservationsEventByIdData = {
    body?: never;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/manager/reservations/event/{id}';
};

export type GetApiManagerReservationsEventByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiManagerReservationsEventByIdResponses = {
    /**
     * OK
     */
    200: DetailedReservationResponseDto[];
};

export type GetApiManagerReservationsEventByIdResponse = GetApiManagerReservationsEventByIdResponses[keyof GetApiManagerReservationsEventByIdResponses];

export type DeleteApiManagerReservationsByIdData = {
    body?: never;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/manager/reservations/{id}';
};

export type DeleteApiManagerReservationsByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type DeleteApiManagerReservationsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiManagerReservationsByIdData = {
    body?: never;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/manager/reservations/{id}';
};

export type GetApiManagerReservationsByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiManagerReservationsByIdResponses = {
    /**
     * OK
     */
    200: DetailedReservationResponseDto;
};

export type GetApiManagerReservationsByIdResponse = GetApiManagerReservationsByIdResponses[keyof GetApiManagerReservationsByIdResponses];

export type PutApiManagerReservationsByIdData = {
    body: ReservationRequestDto;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/manager/reservations/{id}';
};

export type PutApiManagerReservationsByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PutApiManagerReservationsByIdResponses = {
    /**
     * OK
     */
    200: DetailedReservationResponseDto;
};

export type PutApiManagerReservationsByIdResponse = PutApiManagerReservationsByIdResponses[keyof PutApiManagerReservationsByIdResponses];

export type GetApiManagerSeatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/manager/seats';
};

export type GetApiManagerSeatsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiManagerSeatsResponses = {
    /**
     * OK
     */
    200: SeatResponseDto[];
};

export type GetApiManagerSeatsResponse = GetApiManagerSeatsResponses[keyof GetApiManagerSeatsResponses];

export type PostApiManagerSeatsData = {
    body: SeatRequestDto;
    path?: never;
    query?: never;
    url: '/api/manager/seats';
};

export type PostApiManagerSeatsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiManagerSeatsResponses = {
    /**
     * OK
     */
    200: SeatResponseDto;
};

export type PostApiManagerSeatsResponse = PostApiManagerSeatsResponses[keyof PostApiManagerSeatsResponses];

export type DeleteApiManagerSeatsByIdData = {
    body?: never;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/manager/seats/{id}';
};

export type DeleteApiManagerSeatsByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type DeleteApiManagerSeatsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiManagerSeatsByIdData = {
    body?: never;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/manager/seats/{id}';
};

export type GetApiManagerSeatsByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiManagerSeatsByIdResponses = {
    /**
     * OK
     */
    200: SeatResponseDto;
};

export type GetApiManagerSeatsByIdResponse = GetApiManagerSeatsByIdResponses[keyof GetApiManagerSeatsByIdResponses];

export type PutApiManagerSeatsByIdData = {
    body: SeatRequestDto;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/manager/seats/{id}';
};

export type PutApiManagerSeatsByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PutApiManagerSeatsByIdResponses = {
    /**
     * OK
     */
    200: SeatResponseDto;
};

export type PutApiManagerSeatsByIdResponse = PutApiManagerSeatsByIdResponses[keyof PutApiManagerSeatsByIdResponses];

export type GetApiUserConfirmEmailData = {
    body?: never;
    path?: never;
    query?: {
        id?: bigint;
        token?: string;
    };
    url: '/api/user/confirm-email';
};

export type GetApiUserConfirmEmailErrors = {
    /**
     * Invalid token
     */
    400: unknown;
    /**
     * Token not found
     */
    404: unknown;
    /**
     * Token expired
     */
    410: unknown;
};

export type GetApiUserConfirmEmailResponses = {
    /**
     * Email confirmed successfully
     */
    200: unknown;
};

export type GetApiUserEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/events';
};

export type GetApiUserEventsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiUserEventsResponses = {
    /**
     * OK
     */
    200: EventResponseDto[];
};

export type GetApiUserEventsResponse = GetApiUserEventsResponses[keyof GetApiUserEventsResponses];

export type GetApiUserReservationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/reservations';
};

export type GetApiUserReservationsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiUserReservationsResponses = {
    /**
     * OK
     */
    200: ReservationResponseDto[];
};

export type GetApiUserReservationsResponse = GetApiUserReservationsResponses[keyof GetApiUserReservationsResponses];

export type PostApiUserReservationsData = {
    body: ReservationsRequestCreateDto;
    path?: never;
    query?: never;
    url: '/api/user/reservations';
};

export type PostApiUserReservationsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiUserReservationsResponses = {
    /**
     * OK
     */
    200: ReservationResponseDto[];
};

export type PostApiUserReservationsResponse = PostApiUserReservationsResponses[keyof PostApiUserReservationsResponses];

export type DeleteApiUserReservationsByIdData = {
    body?: never;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/user/reservations/{id}';
};

export type DeleteApiUserReservationsByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type DeleteApiUserReservationsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiUserReservationsByIdResponse = DeleteApiUserReservationsByIdResponses[keyof DeleteApiUserReservationsByIdResponses];

export type GetApiUserReservationsByIdData = {
    body?: never;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/user/reservations/{id}';
};

export type GetApiUserReservationsByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiUserReservationsByIdResponses = {
    /**
     * OK
     */
    200: ReservationResponseDto;
};

export type GetApiUserReservationsByIdResponse = GetApiUserReservationsByIdResponses[keyof GetApiUserReservationsByIdResponses];

export type PostApiUsersAdminData = {
    body: UserCreationDto;
    path?: never;
    query?: never;
    url: '/api/users/admin';
};

export type PostApiUsersAdminErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiUsersAdminResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type PostApiUsersAdminResponse = PostApiUsersAdminResponses[keyof PostApiUsersAdminResponses];

export type DeleteApiUsersAdminByIdData = {
    body?: never;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/users/admin/{id}';
};

export type DeleteApiUsersAdminByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type DeleteApiUsersAdminByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiUsersAdminByIdResponse = DeleteApiUsersAdminByIdResponses[keyof DeleteApiUsersAdminByIdResponses];

export type GetApiUsersAdminByIdData = {
    body?: never;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/users/admin/{id}';
};

export type GetApiUsersAdminByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiUsersAdminByIdResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetApiUsersAdminByIdResponse = GetApiUsersAdminByIdResponses[keyof GetApiUsersAdminByIdResponses];

export type PutApiUsersAdminByIdData = {
    body: AdminUserUpdateDto;
    path: {
        id: bigint;
    };
    query?: never;
    url: '/api/users/admin/{id}';
};

export type PutApiUsersAdminByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PutApiUsersAdminByIdResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type PutApiUsersAdminByIdResponse = PutApiUsersAdminByIdResponses[keyof PutApiUsersAdminByIdResponses];

export type GetApiUsersManagerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/manager';
};

export type GetApiUsersManagerErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiUsersManagerResponses = {
    /**
     * OK
     */
    200: LimitedUserInfoDto[];
};

export type GetApiUsersManagerResponse = GetApiUsersManagerResponses[keyof GetApiUsersManagerResponses];

export type GetApiUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetApiUsersMeErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiUsersMeResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type GetApiUsersMeResponse = GetApiUsersMeResponses[keyof GetApiUsersMeResponses];

export type PutApiUsersMeData = {
    body: UserProfileUpdateDto;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type PutApiUsersMeErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PutApiUsersMeResponses = {
    /**
     * OK
     */
    200: UserDto;
};

export type PutApiUsersMeResponse = PutApiUsersMeResponses[keyof PutApiUsersMeResponses];

export type GetApiUsersRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/roles';
};

export type GetApiUsersRolesErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiUsersRolesResponses = {
    /**
     * OK
     */
    200: string[];
};

export type GetApiUsersRolesResponse = GetApiUsersRolesResponses[keyof GetApiUsersRolesResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | 'http://0.0.0.0:8080' | (string & {});
};