version: '3.8'

services:
  nginx:
    image: nginx:1.29
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    image: ghcr.io/felixhertweck/seatreservation-frontend:main
    # ports:
    #   - "3000:3000" 
    networks:
      - app-network

  backend:    
    user: "${UID}:${GID}"
    image: ghcr.io/felixhertweck/seatreservation-backend:main

    # Uncomment this line to use the native image
    # image: ghcr.io/felixhertweck/seatreservation-backend-native:main

    # ports:
    #   - "8080:8080" 
    volumes:
      - ./keys:/deployments/keys:ro

    # Override application.yaml
    #  - ./application.yaml:/deployments/config/application.yaml

    environment:
      # Application configuration
      - APP_URL=${APP_URL}

      # Email configuration
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

      # Database configuration
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    networks:
      - app-network

    depends_on:
      - db

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=seatReservation
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      
    # ports:
    #  - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    external: false

volumes:
  db_data: