apiVersion: 1

policies:
  - orgId: 1
    receiver: critical-email
    group_by: ["alertname"]
    routes:
      - receiver: critical-email
        matchers:
          - severity = critical
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
