smallrye:
  jwt:
    new-token:
      issuer: http://localhost:8081

quarkus:
  mailer:
    mock: true
  hibernate-orm:
    sql-load-script: import-test.sql

email:
  redirect-url: http://localhost:8081