/*
 * #%L
 * seat-reservation
 * %%
 * Copyright (C) 2025 Felix Hertweck
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package de.felixhertweck.seatreservation.security.service;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.ws.rs.client.Client;
import jakarta.ws.rs.client.ClientBuilder;
import jakarta.ws.rs.client.Entity;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.jboss.logging.Logger;

/** Service for verifying CAP (Community Authentication Platform) CAPTCHA tokens. */
@ApplicationScoped
public class CapVerifierService {

    private static final Logger LOG = Logger.getLogger(CapVerifierService.class);

    @ConfigProperty(name = "cap.api.url")
    String capApiUrl;

    @ConfigProperty(name = "cap.site.key")
    String capSiteKey;

    @ConfigProperty(name = "cap.secret.key")
    String capSecretKey;

    private final ObjectMapper mapper = new ObjectMapper();

    /**
     * Verifies a CAP CAPTCHA token by sending it to the CAP server.
     *
     * @param clientToken the token generated by the CAP widget on the client side
     * @return true if the token is valid, false otherwise
     */
    public boolean verifyToken(String clientToken) {
        if (clientToken == null || clientToken.isBlank()) {
            LOG.warnf("CAP token validation attempted with empty token");
            return false;
        }

        try {
            // Construct the verification URL
            String verifyUrl = String.format("%s/%s/siteverify", capApiUrl, capSiteKey);

            // Build the request payload
            String jsonPayload =
                    String.format(
                            "{\"secret\":\"%s\", \"response\":\"%s\"}", capSecretKey, clientToken);

            // Create client and send request
            Client client = ClientBuilder.newClient();
            Response response =
                    client.target(verifyUrl)
                            .request(MediaType.APPLICATION_JSON)
                            .post(Entity.json(jsonPayload));

            // Parse the response
            String responseBody = response.readEntity(String.class);
            JsonNode rootNode = mapper.readTree(responseBody);

            boolean isValid = rootNode.path("success").asBoolean(false);

            LOG.debugf("CAP token verification result: %s", isValid);

            client.close();
            return isValid;

        } catch (Exception e) {
            LOG.errorf(e, "Error verifying CAP token");
            return false;
        }
    }
}
