// This file is auto-generated by @hey-api/openapi-ts

import type { GetApiAuthWebauthnCredentialsResponse, GetApiManagerEventsByIdResponse, GetApiManagerEventsResponse, GetApiManagerReservationsByIdResponse, GetApiManagerReservationsEventByIdResponse, GetApiManagerReservationsResponse, GetApiSupervisorCheckinEventsResponse, GetApiUserEventsResponse, GetApiUserReservationsByIdResponse, GetApiUserReservationsResponse, GetApiUsersMe2FaResponse, PostApiManagerEventsResponse, PostApiManagerReservationsBlockResponse, PostApiManagerReservationsResponse, PostApiSupervisorCheckinInfoByUsernameResponse, PostApiSupervisorCheckinInfoResponse, PostApiUserReservationsResponse, PostApiUserSeatcartByEventIdBySeatIdResponse, PostApiUsersMe2FaDisableResponse, PostApiUsersMe2FaEnableResponse, PutApiManagerEventsByIdResponse, PutApiUsersMe2FaSettingsResponse } from './types.gen';

const instantSchemaResponseTransformer = (data: any) => {
    data = new Date(data);
    return data;
};

const webAuthnCredentialDtoSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = instantSchemaResponseTransformer(data.createdAt);
    }
    if (data.lastUsedAt) {
        data.lastUsedAt = instantSchemaResponseTransformer(data.lastUsedAt);
    }
    return data;
};

export const getApiAuthWebauthnCredentialsResponseTransformer = async (data: any): Promise<GetApiAuthWebauthnCredentialsResponse> => {
    data = data.map((item: any) => webAuthnCredentialDtoSchemaResponseTransformer(item));
    return data;
};

const eventResponseDtoSchemaResponseTransformer = (data: any) => {
    if (data.startTime) {
        data.startTime = instantSchemaResponseTransformer(data.startTime);
    }
    if (data.endTime) {
        data.endTime = instantSchemaResponseTransformer(data.endTime);
    }
    if (data.bookingDeadline) {
        data.bookingDeadline = instantSchemaResponseTransformer(data.bookingDeadline);
    }
    if (data.bookingStartTime) {
        data.bookingStartTime = instantSchemaResponseTransformer(data.bookingStartTime);
    }
    if (data.reminderSendDate) {
        data.reminderSendDate = instantSchemaResponseTransformer(data.reminderSendDate);
    }
    return data;
};

export const getApiManagerEventsResponseTransformer = async (data: any): Promise<GetApiManagerEventsResponse> => {
    data = data.map((item: any) => eventResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const postApiManagerEventsResponseTransformer = async (data: any): Promise<PostApiManagerEventsResponse> => {
    data = eventResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const getApiManagerEventsByIdResponseTransformer = async (data: any): Promise<GetApiManagerEventsByIdResponse> => {
    data = eventResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const putApiManagerEventsByIdResponseTransformer = async (data: any): Promise<PutApiManagerEventsByIdResponse> => {
    data = eventResponseDtoSchemaResponseTransformer(data);
    return data;
};

const reservationResponseDtoSchemaResponseTransformer = (data: any) => {
    if (data.reservationDateTime) {
        data.reservationDateTime = instantSchemaResponseTransformer(data.reservationDateTime);
    }
    return data;
};

export const getApiManagerReservationsResponseTransformer = async (data: any): Promise<GetApiManagerReservationsResponse> => {
    data = data.map((item: any) => reservationResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const postApiManagerReservationsResponseTransformer = async (data: any): Promise<PostApiManagerReservationsResponse> => {
    data = data.map((item: any) => reservationResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const postApiManagerReservationsBlockResponseTransformer = async (data: any): Promise<PostApiManagerReservationsBlockResponse> => {
    data = data.map((item: any) => reservationResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const getApiManagerReservationsEventByIdResponseTransformer = async (data: any): Promise<GetApiManagerReservationsEventByIdResponse> => {
    data = data.map((item: any) => reservationResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const getApiManagerReservationsByIdResponseTransformer = async (data: any): Promise<GetApiManagerReservationsByIdResponse> => {
    data = reservationResponseDtoSchemaResponseTransformer(data);
    return data;
};

const supervisorEventResponseDtoSchemaResponseTransformer = (data: any) => {
    if (data.startTime) {
        data.startTime = instantSchemaResponseTransformer(data.startTime);
    }
    if (data.endTime) {
        data.endTime = instantSchemaResponseTransformer(data.endTime);
    }
    if (data.bookingDeadline) {
        data.bookingDeadline = instantSchemaResponseTransformer(data.bookingDeadline);
    }
    return data;
};

export const getApiSupervisorCheckinEventsResponseTransformer = async (data: any): Promise<GetApiSupervisorCheckinEventsResponse> => {
    data = data.map((item: any) => supervisorEventResponseDtoSchemaResponseTransformer(item));
    return data;
};

const supervisorReservationResponseDtoSchemaResponseTransformer = (data: any) => {
    if (data.reservationDateTime) {
        data.reservationDateTime = instantSchemaResponseTransformer(data.reservationDateTime);
    }
    if (data.reservationDate) {
        data.reservationDate = instantSchemaResponseTransformer(data.reservationDate);
    }
    return data;
};

const checkInInfoResponseDtoSchemaResponseTransformer = (data: any) => {
    if (data.reservations) {
        data.reservations = data.reservations.map((item: any) => supervisorReservationResponseDtoSchemaResponseTransformer(item));
    }
    return data;
};

export const postApiSupervisorCheckinInfoResponseTransformer = async (data: any): Promise<PostApiSupervisorCheckinInfoResponse> => {
    data = checkInInfoResponseDtoSchemaResponseTransformer(data);
    return data;
};

export const postApiSupervisorCheckinInfoByUsernameResponseTransformer = async (data: any): Promise<PostApiSupervisorCheckinInfoByUsernameResponse> => {
    data = checkInInfoResponseDtoSchemaResponseTransformer(data);
    return data;
};

const userEventResponseDtoSchemaResponseTransformer = (data: any) => {
    if (data.startTime) {
        data.startTime = instantSchemaResponseTransformer(data.startTime);
    }
    if (data.endTime) {
        data.endTime = instantSchemaResponseTransformer(data.endTime);
    }
    if (data.bookingDeadline) {
        data.bookingDeadline = instantSchemaResponseTransformer(data.bookingDeadline);
    }
    if (data.bookingStartTime) {
        data.bookingStartTime = instantSchemaResponseTransformer(data.bookingStartTime);
    }
    return data;
};

export const getApiUserEventsResponseTransformer = async (data: any): Promise<GetApiUserEventsResponse> => {
    data = data.map((item: any) => userEventResponseDtoSchemaResponseTransformer(item));
    return data;
};

const userReservationResponseDtoSchemaResponseTransformer = (data: any) => {
    if (data.reservationDateTime) {
        data.reservationDateTime = instantSchemaResponseTransformer(data.reservationDateTime);
    }
    return data;
};

export const getApiUserReservationsResponseTransformer = async (data: any): Promise<GetApiUserReservationsResponse> => {
    data = data.map((item: any) => userReservationResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const postApiUserReservationsResponseTransformer = async (data: any): Promise<PostApiUserReservationsResponse> => {
    data = data.map((item: any) => userReservationResponseDtoSchemaResponseTransformer(item));
    return data;
};

export const getApiUserReservationsByIdResponseTransformer = async (data: any): Promise<GetApiUserReservationsByIdResponse> => {
    data = userReservationResponseDtoSchemaResponseTransformer(data);
    return data;
};

const seatCartEntryDtoSchemaResponseTransformer = (data: any) => {
    if (data.expiresAt) {
        data.expiresAt = instantSchemaResponseTransformer(data.expiresAt);
    }
    return data;
};

export const postApiUserSeatcartByEventIdBySeatIdResponseTransformer = async (data: any): Promise<PostApiUserSeatcartByEventIdBySeatIdResponse> => {
    data = seatCartEntryDtoSchemaResponseTransformer(data);
    return data;
};

const twoFactorStatusDtoSchemaResponseTransformer = (data: any) => {
    if (data.remainingBackupCodes) {
        data.remainingBackupCodes = BigInt(data.remainingBackupCodes.toString());
    }
    return data;
};

export const getApiUsersMe2FaResponseTransformer = async (data: any): Promise<GetApiUsersMe2FaResponse> => {
    data = twoFactorStatusDtoSchemaResponseTransformer(data);
    return data;
};

export const postApiUsersMe2FaDisableResponseTransformer = async (data: any): Promise<PostApiUsersMe2FaDisableResponse> => {
    data = twoFactorStatusDtoSchemaResponseTransformer(data);
    return data;
};

export const postApiUsersMe2FaEnableResponseTransformer = async (data: any): Promise<PostApiUsersMe2FaEnableResponse> => {
    data = twoFactorStatusDtoSchemaResponseTransformer(data);
    return data;
};

export const putApiUsersMe2FaSettingsResponseTransformer = async (data: any): Promise<PutApiUsersMe2FaSettingsResponse> => {
    data = twoFactorStatusDtoSchemaResponseTransformer(data);
    return data;
};
