// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | 'http://0.0.0.0:8080' | (string & {});
};

export type AdminUserCreationDto = {
    username: string;
    email?: string;
    password: string;
    firstname: string;
    lastname: string;
    sendEmailVerification: boolean;
    roles: Array<string>;
    tags: Array<string>;
};

export type AdminUserUpdateDto = {
    email?: string;
    emailVerified: boolean;
    sendEmailVerification: boolean;
    firstname: string;
    lastname: string;
    password?: string;
    tags: Array<string>;
    roles: Array<string>;
};

export type AreaDto = {
    id?: Uuid;
    name?: string;
    seatIds?: Array<string>;
    boundary?: Array<CoordinateDto>;
};

export type AreaRequestDto = {
    name: string;
    boundary?: Array<CoordinateDto>;
    eventLocationId: Uuid;
};

export type AreaResponseDto = {
    id?: Uuid;
    name?: string;
    boundary?: Array<CoordinateDto>;
    eventLocationId?: Uuid;
};

export type BlockSeatsRequestDto = {
    eventId?: Uuid;
    seatIds?: Array<string>;
};

export type CheckInInfoRequestDto = {
    userId: Uuid;
    eventId: Uuid;
    checkInTokens?: Array<string>;
};

export type CheckInInfoResponseDto = {
    reservations?: Array<SupervisorReservationResponseDto>;
    user?: LimitedUserInfoDto;
};

export type CheckInProcessRequestDto = {
    userId: Uuid;
    eventId: Uuid;
    checkIn?: Array<string>;
    cancel?: Array<string>;
};

export type CoordinateDto = {
    xCoordinate?: number;
    yCoordinate?: number;
};

export type EntranceRequestDto = {
    eventLocationId: Uuid;
    name: string;
};

export type EntranceResponseDto = {
    id?: Uuid;
    name?: string;
    eventLocationId?: Uuid;
};

export type EventLocationMakerDto = {
    id?: Uuid;
    label?: string;
    coordinate?: CoordinateDto;
    eventLocationId?: Uuid;
};

export type EventLocationRequestDto = {
    name: string;
    address: string;
    capacity: number;
    markers?: Array<ImportMarkerDto>;
    areas?: Array<ImportAreaDto>;
    seats?: Array<ImportSeatDto>;
};

export type EventLocationResponseDto = {
    id?: Uuid;
    name?: string;
    address?: string;
    capacity?: number;
    manager?: LimitedUserInfoDto;
    seatIds?: Array<string>;
    markers?: Array<EventLocationMakerDto>;
    areas?: Array<AreaDto>;
};

export type EventLocationUpdateDto = {
    name: string;
    address: string;
    capacity: number;
};

export type EventRequestDto = {
    name: string;
    description: string;
    startTime: Instant;
    endTime: Instant;
    bookingDeadline: Instant;
    bookingStartTime: Instant;
    reminderSendDate?: Instant;
    eventLocationId: Uuid;
    supervisorIds?: Array<string>;
};

export type EventResponseDto = {
    id?: Uuid;
    name?: string;
    description?: string;
    startTime?: Instant;
    endTime?: Instant;
    bookingDeadline?: Instant;
    bookingStartTime?: Instant;
    reminderSendDate?: Instant;
    isReminderSent?: boolean;
    seatStatuses?: Array<SeatStatusDto>;
    eventUserAllowancesIds?: Array<string>;
    eventLocationId?: Uuid;
    managerId?: Uuid;
    supervisorIds?: Array<string>;
};

export type EventUserAllowanceUpdateDto = {
    id: Uuid;
    eventId: Uuid;
    userId: Uuid;
    reservationsAllowedCount: number;
};

export type EventUserAllowancesCreateDto = {
    eventId: Uuid;
    userIds: Array<string>;
    reservationsAllowedCount: number;
};

export type EventUserAllowancesDto = {
    id?: Uuid;
    eventId?: Uuid;
    userId?: Uuid;
    reservationsAllowedCount?: number;
};

export type ImportAreaDto = {
    name: string;
    boundary?: Array<CoordinateDto>;
};

export type ImportMarkerDto = {
    label: string;
    coordinate: CoordinateDto;
};

export type ImportSeatDto = {
    seatNumber: string;
    coordinate: CoordinateDto;
    seatRow?: string;
    entrance?: string;
    area?: string;
};

export type Instant = Date;

export type LimitedUserInfoDto = {
    id?: Uuid;
    username?: string;
    tags?: Array<string>;
};

export type LoginLockedDto = {
    message?: string;
    retryAfter?: Instant;
};

export type LoginRequestDto = {
    username: string;
    password: string;
};

export type MakerRequestDto = {
    label: string;
    coordinate: CoordinateDto;
    eventLocationId: Uuid;
};

export type RegisterRequestDto = {
    username: string;
    firstname: string;
    lastname: string;
    email: string;
    password: string;
};

export type RegistrationStatusDto = {
    enabled?: boolean;
};

export const ReservationLiveStatus = {
    CHECKED_IN: 'CHECKED_IN',
    CANCELLED: 'CANCELLED',
    NO_SHOW: 'NO_SHOW'
} as const;

export type ReservationLiveStatus = typeof ReservationLiveStatus[keyof typeof ReservationLiveStatus];

export type ReservationRequestDto = {
    eventId: Uuid;
    userId: Uuid;
    seatIds: Array<string>;
    deductAllowance?: boolean;
};

export type ReservationResponseDto = {
    id?: Uuid;
    user?: UserDto;
    eventId?: Uuid;
    seat?: SeatDto;
    reservationDateTime?: Instant;
    status?: ReservationStatus;
    liveStatus?: ReservationLiveStatus;
};

export const ReservationStatus = { RESERVED: 'RESERVED', BLOCKED: 'BLOCKED' } as const;

export type ReservationStatus = typeof ReservationStatus[keyof typeof ReservationStatus];

export type SeatDto = {
    id?: Uuid;
    seatNumber?: string;
    seatRow?: string;
    locationId?: Uuid;
    coordinate?: CoordinateDto;
    entrance?: string;
    area?: string;
    entranceId?: Uuid;
    areaId?: Uuid;
};

export type SeatRequestDto = {
    seatNumber: string;
    eventLocationId: Uuid;
    coordinate: CoordinateDto;
    seatRow: string;
    entranceId?: Uuid;
    areaId?: Uuid;
};

export type SeatStatusDto = {
    seatId?: Uuid;
    status?: ReservationStatus;
};

/**
 * Event location details for supervisor view
 */
export type SupervisorEventLocationDto = {
    id?: Uuid;
    name?: string;
    seats?: Array<SeatDto>;
    markers?: Array<EventLocationMakerDto>;
    areas?: Array<AreaDto>;
};

export type SupervisorEventResponseDto = {
    id?: Uuid;
    name?: string;
    description?: string;
    startTime?: Instant;
    endTime?: Instant;
};

export type SupervisorReservationResponseDto = {
    id?: Uuid;
    userId?: Uuid;
    username?: string;
    eventId?: Uuid;
    seat?: SeatDto;
    reservationDateTime?: Instant;
    status?: ReservationStatus;
    liveStatus?: ReservationLiveStatus;
    reservationDate?: Instant;
};

/**
 * Seat reservation status for supervisor view
 */
export type SupervisorSeatStatusDto = {
    seatId?: Uuid;
    reservationId?: Uuid;
    status?: ReservationStatus;
    liveStatus?: ReservationLiveStatus;
};

export type Uuid = string;

export type UserDto = {
    id?: Uuid;
    username?: string;
    firstname?: string;
    lastname?: string;
    email?: string;
    emailVerified?: boolean;
    emailVerificationSent?: boolean;
    roles?: Array<string>;
    tags?: Array<string>;
};

export type UserEventLocationResponseDto = {
    id?: Uuid;
    name?: string;
    address?: string;
    capacity?: number;
    manager?: LimitedUserInfoDto;
    seats?: Array<SeatDto>;
    markers?: Array<EventLocationMakerDto>;
    areas?: Array<AreaDto>;
};

export type UserEventResponseDto = {
    id?: Uuid;
    name?: string;
    description?: string;
    startTime?: Instant;
    endTime?: Instant;
    bookingDeadline?: Instant;
    bookingStartTime?: Instant;
    seatStatuses?: Array<SeatStatusDto>;
    locationId?: Uuid;
    reservationsAllowed?: number;
};

export type UserProfileUpdateDto = {
    email: string;
    firstname: string;
    lastname: string;
    password?: string;
    tags: Array<string>;
};

export type UserReservationResponseDto = {
    id?: Uuid;
    userId?: Uuid;
    eventId?: Uuid;
    seat?: SeatDto;
    reservationDateTime?: Instant;
    checkInCode?: string;
};

export type UserReservationsRequestDto = {
    eventId: Uuid;
    seatIds: Array<string>;
};

export type VerifyEmailCodeRequestDto = {
    verificationCode: string;
};

export type WebAuthnCredentialDto = {
    id?: Uuid;
    label?: string;
    createdAt?: Instant;
    lastUsedAt?: Instant;
};

export type WebAuthnCredentialUpdateDto = {
    label: string;
};

export type WebAuthnRegistrationStartDto = {
    username: string;
    firstname: string;
    lastname: string;
    email: string;
};

export type WebAuthnStatusDto = {
    hasPasskey?: boolean;
    hasPassword?: boolean;
};

export type PostApiAuthLoginData = {
    body: LoginRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type PostApiAuthLoginErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized: Invalid credentials
     */
    401: unknown;
    /**
     * Too Many Requests: Account temporarily locked due to too many failed login attempts
     */
    429: LoginLockedDto;
};

export type PostApiAuthLoginError = PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
    /**
     * Login successful, JWT cookie set
     */
    200: unknown;
};

export type PostApiAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type PostApiAuthLogoutErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only authenticated users can access this resource
     */
    403: unknown;
};

export type PostApiAuthLogoutResponses = {
    /**
     * Logout successful, JWT and refresh token cookies cleared
     */
    200: unknown;
};

export type PostApiAuthLogoutAllDevicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logoutAllDevices';
};

export type PostApiAuthLogoutAllDevicesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only authenticated users can access this resource
     */
    403: unknown;
};

export type PostApiAuthLogoutAllDevicesResponses = {
    /**
     * Logout from all devices successful
     */
    200: unknown;
};

export type PostApiAuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type PostApiAuthRefreshErrors = {
    /**
     * Unauthorized: Invalid or expired token
     */
    401: unknown;
};

export type PostApiAuthRefreshResponses = {
    /**
     * Token refresh successful, new JWT cookie set
     */
    200: unknown;
};

export type PostApiAuthRegisterData = {
    body: RegisterRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type PostApiAuthRegisterErrors = {
    /**
     * Bad Request: Invalid user data
     */
    400: unknown;
    /**
     * Forbidden: Registration is disabled
     */
    403: unknown;
    /**
     * Conflict: User with this username already exists
     */
    409: unknown;
};

export type PostApiAuthRegisterResponses = {
    /**
     * Registration successful, JWT cookie set
     */
    200: unknown;
};

export type GetApiAuthRegistrationStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/registration-status';
};

export type GetApiAuthRegistrationStatusResponses = {
    /**
     * Registration status retrieved successfully
     */
    200: RegistrationStatusDto;
};

export type GetApiAuthRegistrationStatusResponse = GetApiAuthRegistrationStatusResponses[keyof GetApiAuthRegistrationStatusResponses];

export type GetApiAuthWebauthnCredentialsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/webauthn/credentials';
};

export type GetApiAuthWebauthnCredentialsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiAuthWebauthnCredentialsResponses = {
    /**
     * Passkeys listed
     */
    200: Array<WebAuthnCredentialDto>;
};

export type GetApiAuthWebauthnCredentialsResponse = GetApiAuthWebauthnCredentialsResponses[keyof GetApiAuthWebauthnCredentialsResponses];

export type DeleteApiAuthWebauthnCredentialsByIdData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/auth/webauthn/credentials/{id}';
};

export type DeleteApiAuthWebauthnCredentialsByIdErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * Passkey not found
     */
    404: unknown;
    /**
     * Cannot delete the last passkey of a password-less account
     */
    409: unknown;
};

export type DeleteApiAuthWebauthnCredentialsByIdResponses = {
    /**
     * Passkey deleted
     */
    204: void;
};

export type DeleteApiAuthWebauthnCredentialsByIdResponse = DeleteApiAuthWebauthnCredentialsByIdResponses[keyof DeleteApiAuthWebauthnCredentialsByIdResponses];

export type PutApiAuthWebauthnCredentialsByIdData = {
    body: WebAuthnCredentialUpdateDto;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/auth/webauthn/credentials/{id}';
};

export type PutApiAuthWebauthnCredentialsByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * Passkey not found
     */
    404: unknown;
};

export type PutApiAuthWebauthnCredentialsByIdResponses = {
    /**
     * Passkey renamed
     */
    200: unknown;
};

export type PostApiAuthWebauthnLoginData = {
    body: string;
    path?: never;
    query?: never;
    url: '/api/auth/webauthn/login';
};

export type PostApiAuthWebauthnLoginErrors = {
    /**
     * Invalid assertion
     */
    401: unknown;
};

export type PostApiAuthWebauthnLoginResponses = {
    /**
     * Login successful, JWT cookie set
     */
    200: unknown;
};

export type PostApiAuthWebauthnLoginOptionsData = {
    body?: never;
    path?: never;
    query?: {
        username?: string;
    };
    url: '/api/auth/webauthn/login/options';
};

export type PostApiAuthWebauthnLoginOptionsResponses = {
    /**
     * Login options created
     */
    200: string;
};

export type PostApiAuthWebauthnLoginOptionsResponse = PostApiAuthWebauthnLoginOptionsResponses[keyof PostApiAuthWebauthnLoginOptionsResponses];

export type PostApiAuthWebauthnRegisterData = {
    body: string;
    headers?: {
        'User-Agent'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/webauthn/register';
};

export type PostApiAuthWebauthnRegisterErrors = {
    /**
     * Invalid attestation
     */
    400: unknown;
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiAuthWebauthnRegisterResponses = {
    /**
     * Passkey registered
     */
    200: unknown;
};

export type PostApiAuthWebauthnRegisterNewData = {
    body: string;
    headers?: {
        'User-Agent'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/auth/webauthn/register-new';
};

export type PostApiAuthWebauthnRegisterNewErrors = {
    /**
     * Invalid attestation
     */
    400: unknown;
    /**
     * Registration is disabled
     */
    403: unknown;
    /**
     * Username already exists
     */
    409: unknown;
};

export type PostApiAuthWebauthnRegisterNewResponses = {
    /**
     * Account created, JWT cookie set
     */
    200: unknown;
};

export type PostApiAuthWebauthnRegisterNewOptionsData = {
    body: WebAuthnRegistrationStartDto;
    path?: never;
    query?: never;
    url: '/api/auth/webauthn/register-new/options';
};

export type PostApiAuthWebauthnRegisterNewOptionsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Registration is disabled
     */
    403: unknown;
    /**
     * Username already exists
     */
    409: unknown;
};

export type PostApiAuthWebauthnRegisterNewOptionsResponses = {
    /**
     * Registration options created
     */
    200: string;
};

export type PostApiAuthWebauthnRegisterNewOptionsResponse = PostApiAuthWebauthnRegisterNewOptionsResponses[keyof PostApiAuthWebauthnRegisterNewOptionsResponses];

export type PostApiAuthWebauthnRegisterOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/webauthn/register/options';
};

export type PostApiAuthWebauthnRegisterOptionsErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiAuthWebauthnRegisterOptionsResponses = {
    /**
     * Registration options created
     */
    200: string;
};

export type PostApiAuthWebauthnRegisterOptionsResponse = PostApiAuthWebauthnRegisterOptionsResponses[keyof PostApiAuthWebauthnRegisterOptionsResponses];

export type GetApiAuthWebauthnStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/webauthn/status';
};

export type GetApiAuthWebauthnStatusErrors = {
    /**
     * Not Authorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiAuthWebauthnStatusResponses = {
    /**
     * Status retrieved
     */
    200: WebAuthnStatusDto;
};

export type GetApiAuthWebauthnStatusResponse = GetApiAuthWebauthnStatusResponses[keyof GetApiAuthWebauthnStatusResponses];

export type GetApiEmailSeatmapData = {
    body?: never;
    path?: never;
    query?: {
        token?: string;
    };
    url: '/api/email/seatmap';
};

export type GetApiEmailSeatmapResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type GetApiEmailSeatmapResponse = GetApiEmailSeatmapResponses[keyof GetApiEmailSeatmapResponses];

export type DeleteApiManagerAreasData = {
    body?: never;
    path?: never;
    query?: {
        ids?: Array<string>;
    };
    url: '/api/manager/areas';
};

export type DeleteApiManagerAreasErrors = {
    /**
     * Bad Request: Invalid input
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Area with specified ID not found for the current manager
     */
    404: unknown;
    /**
     * Conflict: Area is still referenced by at least one seat
     */
    409: unknown;
};

export type DeleteApiManagerAreasResponses = {
    /**
     * Area(s) deleted successfully
     */
    204: void;
};

export type DeleteApiManagerAreasResponse = DeleteApiManagerAreasResponses[keyof DeleteApiManagerAreasResponses];

export type GetApiManagerAreasData = {
    body?: never;
    path?: never;
    query?: {
        eventLocationId?: Uuid;
    };
    url: '/api/manager/areas';
};

export type GetApiManagerAreasErrors = {
    /**
     * Bad Request: eventLocationId is required
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
};

export type GetApiManagerAreasResponses = {
    /**
     * OK
     */
    200: Array<AreaResponseDto>;
};

export type GetApiManagerAreasResponse = GetApiManagerAreasResponses[keyof GetApiManagerAreasResponses];

export type PostApiManagerAreasData = {
    body: AreaRequestDto;
    path?: never;
    query?: never;
    url: '/api/manager/areas';
};

export type PostApiManagerAreasErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event location not found
     */
    404: unknown;
};

export type PostApiManagerAreasResponses = {
    /**
     * OK
     */
    200: AreaResponseDto;
};

export type PostApiManagerAreasResponse = PostApiManagerAreasResponses[keyof PostApiManagerAreasResponses];

export type GetApiManagerAreasByIdData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/manager/areas/{id}';
};

export type GetApiManagerAreasByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Area with specified ID not found for the current manager
     */
    404: unknown;
};

export type GetApiManagerAreasByIdResponses = {
    /**
     * OK
     */
    200: AreaResponseDto;
};

export type GetApiManagerAreasByIdResponse = GetApiManagerAreasByIdResponses[keyof GetApiManagerAreasByIdResponses];

export type PutApiManagerAreasByIdData = {
    body: AreaRequestDto;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/manager/areas/{id}';
};

export type PutApiManagerAreasByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Area with specified ID not found for the current manager
     */
    404: unknown;
};

export type PutApiManagerAreasByIdResponses = {
    /**
     * OK
     */
    200: AreaResponseDto;
};

export type PutApiManagerAreasByIdResponse = PutApiManagerAreasByIdResponses[keyof PutApiManagerAreasByIdResponses];

export type DeleteApiManagerEntrancesData = {
    body?: never;
    path?: never;
    query?: {
        ids?: Array<string>;
    };
    url: '/api/manager/entrances';
};

export type DeleteApiManagerEntrancesErrors = {
    /**
     * Bad Request: Invalid input
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Entrance with specified ID not found for the current manager
     */
    404: unknown;
    /**
     * Conflict: Entrance is still referenced by at least one seat
     */
    409: unknown;
};

export type DeleteApiManagerEntrancesResponses = {
    /**
     * Entrance(s) deleted successfully
     */
    204: void;
};

export type DeleteApiManagerEntrancesResponse = DeleteApiManagerEntrancesResponses[keyof DeleteApiManagerEntrancesResponses];

export type GetApiManagerEntrancesData = {
    body?: never;
    path?: never;
    query?: {
        eventLocationId?: Uuid;
    };
    url: '/api/manager/entrances';
};

export type GetApiManagerEntrancesErrors = {
    /**
     * Bad Request: eventLocationId is required
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
};

export type GetApiManagerEntrancesResponses = {
    /**
     * OK
     */
    200: Array<EntranceResponseDto>;
};

export type GetApiManagerEntrancesResponse = GetApiManagerEntrancesResponses[keyof GetApiManagerEntrancesResponses];

export type PostApiManagerEntrancesData = {
    body: EntranceRequestDto;
    path?: never;
    query?: never;
    url: '/api/manager/entrances';
};

export type PostApiManagerEntrancesErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event location not found
     */
    404: unknown;
};

export type PostApiManagerEntrancesResponses = {
    /**
     * OK
     */
    200: EntranceResponseDto;
};

export type PostApiManagerEntrancesResponse = PostApiManagerEntrancesResponses[keyof PostApiManagerEntrancesResponses];

export type GetApiManagerEntrancesByIdData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/manager/entrances/{id}';
};

export type GetApiManagerEntrancesByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Entrance with specified ID not found for the current manager
     */
    404: unknown;
};

export type GetApiManagerEntrancesByIdResponses = {
    /**
     * OK
     */
    200: EntranceResponseDto;
};

export type GetApiManagerEntrancesByIdResponse = GetApiManagerEntrancesByIdResponses[keyof GetApiManagerEntrancesByIdResponses];

export type PutApiManagerEntrancesByIdData = {
    body: EntranceRequestDto;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/manager/entrances/{id}';
};

export type PutApiManagerEntrancesByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Entrance with specified ID not found for the current manager
     */
    404: unknown;
};

export type PutApiManagerEntrancesByIdResponses = {
    /**
     * OK
     */
    200: EntranceResponseDto;
};

export type PutApiManagerEntrancesByIdResponse = PutApiManagerEntrancesByIdResponses[keyof PutApiManagerEntrancesByIdResponses];

export type DeleteApiManagerEventlocationsData = {
    body?: never;
    path?: never;
    query?: {
        ids?: Array<string>;
    };
    url: '/api/manager/eventlocations';
};

export type DeleteApiManagerEventlocationsErrors = {
    /**
     * Bad Request: Invalid input
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event location with specified ID not found
     */
    404: unknown;
};

export type DeleteApiManagerEventlocationsResponses = {
    /**
     * OK
     */
    200: unknown;
    /**
     * Event location deleted successfully
     */
    204: void;
};

export type DeleteApiManagerEventlocationsResponse = DeleteApiManagerEventlocationsResponses[keyof DeleteApiManagerEventlocationsResponses];

export type GetApiManagerEventlocationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/manager/eventlocations';
};

export type GetApiManagerEventlocationsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
};

export type GetApiManagerEventlocationsResponses = {
    /**
     * OK
     */
    200: Array<EventLocationResponseDto>;
};

export type GetApiManagerEventlocationsResponse = GetApiManagerEventlocationsResponses[keyof GetApiManagerEventlocationsResponses];

export type PostApiManagerEventlocationsData = {
    body: EventLocationRequestDto;
    path?: never;
    query?: never;
    url: '/api/manager/eventlocations';
};

export type PostApiManagerEventlocationsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Conflict: Event location with this name already exists
     */
    409: unknown;
};

export type PostApiManagerEventlocationsResponses = {
    /**
     * OK
     */
    200: EventLocationResponseDto;
};

export type PostApiManagerEventlocationsResponse = PostApiManagerEventlocationsResponses[keyof PostApiManagerEventlocationsResponses];

export type PutApiManagerEventlocationsByIdData = {
    body: EventLocationUpdateDto;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/manager/eventlocations/{id}';
};

export type PutApiManagerEventlocationsByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event location with specified ID not found
     */
    404: unknown;
    /**
     * Conflict: Event location with this name already exists
     */
    409: unknown;
};

export type PutApiManagerEventlocationsByIdResponses = {
    /**
     * OK
     */
    200: EventLocationResponseDto;
};

export type PutApiManagerEventlocationsByIdResponse = PutApiManagerEventlocationsByIdResponses[keyof PutApiManagerEventlocationsByIdResponses];

export type DeleteApiManagerEventsData = {
    body?: never;
    path?: never;
    query?: {
        ids?: Array<string>;
    };
    url: '/api/manager/events';
};

export type DeleteApiManagerEventsErrors = {
    /**
     * Bad Request: Invalid input
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event with specified ID not found for the current manager
     */
    404: unknown;
};

export type DeleteApiManagerEventsResponses = {
    /**
     * Event deleted
     */
    204: void;
};

export type DeleteApiManagerEventsResponse = DeleteApiManagerEventsResponses[keyof DeleteApiManagerEventsResponses];

export type GetApiManagerEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/manager/events';
};

export type GetApiManagerEventsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
};

export type GetApiManagerEventsResponses = {
    /**
     * OK
     */
    200: Array<EventResponseDto>;
};

export type GetApiManagerEventsResponse = GetApiManagerEventsResponses[keyof GetApiManagerEventsResponses];

export type PostApiManagerEventsData = {
    body: EventRequestDto;
    path?: never;
    query?: never;
    url: '/api/manager/events';
};

export type PostApiManagerEventsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event location not found
     */
    404: unknown;
    /**
     * Conflict: Event with this name already exists in this event location
     */
    409: unknown;
};

export type PostApiManagerEventsResponses = {
    /**
     * OK
     */
    200: EventResponseDto;
};

export type PostApiManagerEventsResponse = PostApiManagerEventsResponses[keyof PostApiManagerEventsResponses];

export type GetApiManagerEventsByIdData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/manager/events/{id}';
};

export type GetApiManagerEventsByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event with specified ID not found for the current manager
     */
    404: unknown;
};

export type GetApiManagerEventsByIdResponses = {
    /**
     * OK
     */
    200: EventResponseDto;
};

export type GetApiManagerEventsByIdResponse = GetApiManagerEventsByIdResponses[keyof GetApiManagerEventsByIdResponses];

export type PutApiManagerEventsByIdData = {
    body: EventRequestDto;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/manager/events/{id}';
};

export type PutApiManagerEventsByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event or event location not found
     */
    404: unknown;
    /**
     * Conflict: Event with this name already exists in this event location
     */
    409: unknown;
};

export type PutApiManagerEventsByIdResponses = {
    /**
     * OK
     */
    200: EventResponseDto;
};

export type PutApiManagerEventsByIdResponse = PutApiManagerEventsByIdResponses[keyof PutApiManagerEventsByIdResponses];

export type DeleteApiManagerMarkersData = {
    body?: never;
    path?: never;
    query?: {
        ids?: Array<string>;
    };
    url: '/api/manager/markers';
};

export type DeleteApiManagerMarkersErrors = {
    /**
     * Bad Request: Invalid input
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Marker with specified ID not found for the current manager
     */
    404: unknown;
};

export type DeleteApiManagerMarkersResponses = {
    /**
     * Marker(s) deleted successfully
     */
    204: void;
};

export type DeleteApiManagerMarkersResponse = DeleteApiManagerMarkersResponses[keyof DeleteApiManagerMarkersResponses];

export type GetApiManagerMarkersData = {
    body?: never;
    path?: never;
    query?: {
        eventLocationId?: Uuid;
    };
    url: '/api/manager/markers';
};

export type GetApiManagerMarkersErrors = {
    /**
     * Bad Request: eventLocationId is required
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
};

export type GetApiManagerMarkersResponses = {
    /**
     * OK
     */
    200: Array<EventLocationMakerDto>;
};

export type GetApiManagerMarkersResponse = GetApiManagerMarkersResponses[keyof GetApiManagerMarkersResponses];

export type PostApiManagerMarkersData = {
    body: MakerRequestDto;
    path?: never;
    query?: never;
    url: '/api/manager/markers';
};

export type PostApiManagerMarkersErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event location not found
     */
    404: unknown;
};

export type PostApiManagerMarkersResponses = {
    /**
     * OK
     */
    200: EventLocationMakerDto;
};

export type PostApiManagerMarkersResponse = PostApiManagerMarkersResponses[keyof PostApiManagerMarkersResponses];

export type GetApiManagerMarkersByIdData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/manager/markers/{id}';
};

export type GetApiManagerMarkersByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Marker with specified ID not found for the current manager
     */
    404: unknown;
};

export type GetApiManagerMarkersByIdResponses = {
    /**
     * OK
     */
    200: EventLocationMakerDto;
};

export type GetApiManagerMarkersByIdResponse = GetApiManagerMarkersByIdResponses[keyof GetApiManagerMarkersByIdResponses];

export type PutApiManagerMarkersByIdData = {
    body: MakerRequestDto;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/manager/markers/{id}';
};

export type PutApiManagerMarkersByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Marker with specified ID not found for the current manager
     */
    404: unknown;
};

export type PutApiManagerMarkersByIdResponses = {
    /**
     * OK
     */
    200: EventLocationMakerDto;
};

export type PutApiManagerMarkersByIdResponse = PutApiManagerMarkersByIdResponses[keyof PutApiManagerMarkersByIdResponses];

export type DeleteApiManagerReservationAllowanceData = {
    body?: never;
    path?: never;
    query?: {
        ids?: Array<string>;
    };
    url: '/api/manager/reservationAllowance';
};

export type DeleteApiManagerReservationAllowanceErrors = {
    /**
     * Bad Request: Invalid input
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Allowance with specified ID not found
     */
    404: unknown;
};

export type DeleteApiManagerReservationAllowanceResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiManagerReservationAllowanceResponse = DeleteApiManagerReservationAllowanceResponses[keyof DeleteApiManagerReservationAllowanceResponses];

export type GetApiManagerReservationAllowanceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/manager/reservationAllowance';
};

export type GetApiManagerReservationAllowanceErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
};

export type GetApiManagerReservationAllowanceResponses = {
    /**
     * List of reservation allowances retrieved successfully
     */
    200: Array<EventUserAllowancesDto>;
};

export type GetApiManagerReservationAllowanceResponse = GetApiManagerReservationAllowanceResponses[keyof GetApiManagerReservationAllowanceResponses];

export type PostApiManagerReservationAllowanceData = {
    body: EventUserAllowancesCreateDto;
    path?: never;
    query?: never;
    url: '/api/manager/reservationAllowance';
};

export type PostApiManagerReservationAllowanceErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event or user not found
     */
    404: unknown;
    /**
     * Conflict: Allowance already exists for this user and event
     */
    409: unknown;
};

export type PostApiManagerReservationAllowanceResponses = {
    /**
     * OK
     */
    200: Array<EventUserAllowancesDto>;
};

export type PostApiManagerReservationAllowanceResponse = PostApiManagerReservationAllowanceResponses[keyof PostApiManagerReservationAllowanceResponses];

export type PutApiManagerReservationAllowanceData = {
    body: EventUserAllowanceUpdateDto;
    path?: never;
    query?: never;
    url: '/api/manager/reservationAllowance';
};

export type PutApiManagerReservationAllowanceErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Allowance with specified ID not found
     */
    404: unknown;
    /**
     * Conflict: Allowance already exists for this user and event
     */
    409: unknown;
};

export type PutApiManagerReservationAllowanceResponses = {
    /**
     * OK
     */
    200: EventUserAllowancesDto;
};

export type PutApiManagerReservationAllowanceResponse = PutApiManagerReservationAllowanceResponses[keyof PutApiManagerReservationAllowanceResponses];

export type GetApiManagerReservationAllowanceEventByEventIdData = {
    body?: never;
    path: {
        eventId: Uuid;
    };
    query?: never;
    url: '/api/manager/reservationAllowance/event/{eventId}';
};

export type GetApiManagerReservationAllowanceEventByEventIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event with specified ID not found
     */
    404: unknown;
};

export type GetApiManagerReservationAllowanceEventByEventIdResponses = {
    /**
     * List of reservation allowances for a specific event retrieved successfully
     */
    200: Array<EventUserAllowancesDto>;
};

export type GetApiManagerReservationAllowanceEventByEventIdResponse = GetApiManagerReservationAllowanceEventByEventIdResponses[keyof GetApiManagerReservationAllowanceEventByEventIdResponses];

export type GetApiManagerReservationAllowanceByIdData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/manager/reservationAllowance/{id}';
};

export type GetApiManagerReservationAllowanceByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Allowance with specified ID not found
     */
    404: unknown;
};

export type GetApiManagerReservationAllowanceByIdResponses = {
    /**
     * Reservation allowance retrieved successfully
     */
    200: EventUserAllowancesDto;
};

export type GetApiManagerReservationAllowanceByIdResponse = GetApiManagerReservationAllowanceByIdResponses[keyof GetApiManagerReservationAllowanceByIdResponses];

export type DeleteApiManagerReservationsData = {
    body?: never;
    path?: never;
    query?: {
        ids?: Array<string>;
    };
    url: '/api/manager/reservations';
};

export type DeleteApiManagerReservationsErrors = {
    /**
     * Bad Request: Invalid input
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Reservation with specified ID not found for the current manager
     */
    404: unknown;
};

export type DeleteApiManagerReservationsResponses = {
    /**
     * Reservation deleted successfully
     */
    204: void;
};

export type DeleteApiManagerReservationsResponse = DeleteApiManagerReservationsResponses[keyof DeleteApiManagerReservationsResponses];

export type GetApiManagerReservationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/manager/reservations';
};

export type GetApiManagerReservationsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
};

export type GetApiManagerReservationsResponses = {
    /**
     * OK
     */
    200: Array<ReservationResponseDto>;
};

export type GetApiManagerReservationsResponse = GetApiManagerReservationsResponses[keyof GetApiManagerReservationsResponses];

export type PostApiManagerReservationsData = {
    body: ReservationRequestDto;
    path?: never;
    query?: never;
    url: '/api/manager/reservations';
};

export type PostApiManagerReservationsErrors = {
    /**
     * Bad Request: Invalid input
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event, user or seat not found
     */
    404: unknown;
    /**
     * Conflict: Seat already reserved or event booking closed
     */
    409: unknown;
};

export type PostApiManagerReservationsResponses = {
    /**
     * OK
     */
    200: Array<ReservationResponseDto>;
};

export type PostApiManagerReservationsResponse = PostApiManagerReservationsResponses[keyof PostApiManagerReservationsResponses];

export type PostApiManagerReservationsBlockData = {
    body: BlockSeatsRequestDto;
    path?: never;
    query?: never;
    url: '/api/manager/reservations/block';
};

export type PostApiManagerReservationsBlockErrors = {
    /**
     * Bad Request: Invalid input
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event or seat not found
     */
    404: unknown;
    /**
     * Conflict: Seat already blocked
     */
    409: unknown;
};

export type PostApiManagerReservationsBlockResponses = {
    /**
     * Seats blocked successfully
     */
    200: Array<ReservationResponseDto>;
};

export type PostApiManagerReservationsBlockResponse = PostApiManagerReservationsBlockResponses[keyof PostApiManagerReservationsBlockResponses];

export type GetApiManagerReservationsEventByIdData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/manager/reservations/event/{id}';
};

export type GetApiManagerReservationsEventByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event with specified ID not found for the current manager
     */
    404: unknown;
};

export type GetApiManagerReservationsEventByIdResponses = {
    /**
     * OK
     */
    200: Array<ReservationResponseDto>;
};

export type GetApiManagerReservationsEventByIdResponse = GetApiManagerReservationsEventByIdResponses[keyof GetApiManagerReservationsEventByIdResponses];

export type GetApiManagerReservationsExportByEventIdCsvData = {
    body?: never;
    path: {
        eventId: Uuid;
    };
    query?: never;
    url: '/api/manager/reservations/export/{eventId}/csv';
};

export type GetApiManagerReservationsExportByEventIdCsvErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - User not authorized
     */
    403: unknown;
    /**
     * Not Found - Event not found
     */
    404: unknown;
    /**
     * Internal Server Error during CSV export
     */
    500: unknown;
};

export type GetApiManagerReservationsExportByEventIdCsvResponses = {
    /**
     * CSV export of reservations for a specific event
     */
    200: unknown;
};

export type GetApiManagerReservationsExportByEventIdPdfData = {
    body?: never;
    path: {
        eventId: Uuid;
    };
    query?: never;
    url: '/api/manager/reservations/export/{eventId}/pdf';
};

export type GetApiManagerReservationsExportByEventIdPdfErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden - User not authorized
     */
    403: unknown;
    /**
     * Not Found - Event not found
     */
    404: unknown;
    /**
     * Internal Server Error during PDF export
     */
    500: unknown;
};

export type GetApiManagerReservationsExportByEventIdPdfResponses = {
    /**
     * PDF export of reservations for a specific event
     */
    200: Blob | File;
};

export type GetApiManagerReservationsExportByEventIdPdfResponse = GetApiManagerReservationsExportByEventIdPdfResponses[keyof GetApiManagerReservationsExportByEventIdPdfResponses];

export type GetApiManagerReservationsByIdData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/manager/reservations/{id}';
};

export type GetApiManagerReservationsByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Reservation with specified ID not found for the current manager
     */
    404: unknown;
};

export type GetApiManagerReservationsByIdResponses = {
    /**
     * OK
     */
    200: ReservationResponseDto;
};

export type GetApiManagerReservationsByIdResponse = GetApiManagerReservationsByIdResponses[keyof GetApiManagerReservationsByIdResponses];

export type DeleteApiManagerSeatsData = {
    body?: never;
    path?: never;
    query?: {
        ids?: Array<string>;
    };
    url: '/api/manager/seats';
};

export type DeleteApiManagerSeatsErrors = {
    /**
     * Bad Request: Invalid input
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Seat with specified ID not found for the current manager
     */
    404: unknown;
};

export type DeleteApiManagerSeatsResponses = {
    /**
     * OK
     */
    200: unknown;
    /**
     * Seat deleted successfully
     */
    204: void;
};

export type DeleteApiManagerSeatsResponse = DeleteApiManagerSeatsResponses[keyof DeleteApiManagerSeatsResponses];

export type GetApiManagerSeatsData = {
    body?: never;
    path?: never;
    query?: {
        eventLocationId?: Uuid;
    };
    url: '/api/manager/seats';
};

export type GetApiManagerSeatsErrors = {
    /**
     * Bad Request: eventLocationId is required
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
};

export type GetApiManagerSeatsResponses = {
    /**
     * OK
     */
    200: Array<SeatDto>;
};

export type GetApiManagerSeatsResponse = GetApiManagerSeatsResponses[keyof GetApiManagerSeatsResponses];

export type PostApiManagerSeatsData = {
    body: SeatRequestDto;
    path?: never;
    query?: never;
    url: '/api/manager/seats';
};

export type PostApiManagerSeatsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event location not found
     */
    404: unknown;
    /**
     * Conflict: Seat with this row and number already exists in this event location
     */
    409: unknown;
};

export type PostApiManagerSeatsResponses = {
    /**
     * OK
     */
    200: SeatDto;
};

export type PostApiManagerSeatsResponse = PostApiManagerSeatsResponses[keyof PostApiManagerSeatsResponses];

export type GetApiManagerSeatsByIdData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/manager/seats/{id}';
};

export type GetApiManagerSeatsByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Seat with specified ID not found for the current manager
     */
    404: unknown;
};

export type GetApiManagerSeatsByIdResponses = {
    /**
     * OK
     */
    200: SeatDto;
};

export type GetApiManagerSeatsByIdResponse = GetApiManagerSeatsByIdResponses[keyof GetApiManagerSeatsByIdResponses];

export type PutApiManagerSeatsByIdData = {
    body: SeatRequestDto;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/manager/seats/{id}';
};

export type PutApiManagerSeatsByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only MANAGER or ADMIN roles can access this resource
     */
    403: unknown;
    /**
     * Not Found: Seat with specified ID not found for the current manager
     */
    404: unknown;
    /**
     * Conflict: Seat with this row and number already exists in this event location
     */
    409: unknown;
};

export type PutApiManagerSeatsByIdResponses = {
    /**
     * OK
     */
    200: SeatDto;
};

export type PutApiManagerSeatsByIdResponse = PutApiManagerSeatsByIdResponses[keyof PutApiManagerSeatsByIdResponses];

export type GetApiSupervisorCheckinEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/supervisor/checkin/events';
};

export type GetApiSupervisorCheckinEventsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type GetApiSupervisorCheckinEventsResponses = {
    /**
     * OK - Events retrieved successfully
     */
    200: Array<SupervisorEventResponseDto>;
};

export type GetApiSupervisorCheckinEventsResponse = GetApiSupervisorCheckinEventsResponses[keyof GetApiSupervisorCheckinEventsResponses];

export type PostApiSupervisorCheckinInfoData = {
    body: CheckInInfoRequestDto;
    path?: never;
    query?: never;
    url: '/api/supervisor/checkin/info';
};

export type PostApiSupervisorCheckinInfoErrors = {
    /**
     * Bad Request - Invalid input parameters
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * Token not found
     */
    404: unknown;
};

export type PostApiSupervisorCheckinInfoResponses = {
    /**
     * OK - Check-in information retrieved successfully
     */
    200: CheckInInfoResponseDto;
};

export type PostApiSupervisorCheckinInfoResponse = PostApiSupervisorCheckinInfoResponses[keyof PostApiSupervisorCheckinInfoResponses];

export type PostApiSupervisorCheckinInfoByUsernameData = {
    body?: never;
    path: {
        username: string;
    };
    query?: never;
    url: '/api/supervisor/checkin/info/{username}';
};

export type PostApiSupervisorCheckinInfoByUsernameErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * User or Reservation not found
     */
    404: unknown;
};

export type PostApiSupervisorCheckinInfoByUsernameResponses = {
    /**
     * OK - Check-in information processed successfully
     */
    200: CheckInInfoResponseDto;
};

export type PostApiSupervisorCheckinInfoByUsernameResponse = PostApiSupervisorCheckinInfoByUsernameResponses[keyof PostApiSupervisorCheckinInfoByUsernameResponses];

export type PostApiSupervisorCheckinProcessData = {
    body: CheckInProcessRequestDto;
    path?: never;
    query?: never;
    url: '/api/supervisor/checkin/process';
};

export type PostApiSupervisorCheckinProcessErrors = {
    /**
     * Bad Request - Invalid input parameters
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
};

export type PostApiSupervisorCheckinProcessResponses = {
    /**
     * No Content - Successfully processed
     */
    204: void;
};

export type PostApiSupervisorCheckinProcessResponse = PostApiSupervisorCheckinProcessResponses[keyof PostApiSupervisorCheckinProcessResponses];

export type GetApiSupervisorCheckinUsernamesByEventIdData = {
    body?: never;
    path: {
        eventId: Uuid;
    };
    query?: never;
    url: '/api/supervisor/checkin/usernames/{eventId}';
};

export type GetApiSupervisorCheckinUsernamesByEventIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Not Allowed
     */
    403: unknown;
    /**
     * Event not found
     */
    404: unknown;
};

export type GetApiSupervisorCheckinUsernamesByEventIdResponses = {
    /**
     * OK - Usernames retrieved successfully
     */
    200: Array<string>;
};

export type GetApiSupervisorCheckinUsernamesByEventIdResponse = GetApiSupervisorCheckinUsernamesByEventIdResponses[keyof GetApiSupervisorCheckinUsernamesByEventIdResponses];

export type GetApiUserEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/events';
};

export type GetApiUserEventsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only authenticated users can access this resource
     */
    403: unknown;
};

export type GetApiUserEventsResponses = {
    /**
     * OK
     */
    200: Array<UserEventResponseDto>;
};

export type GetApiUserEventsResponse = GetApiUserEventsResponses[keyof GetApiUserEventsResponses];

export type GetApiUserLocationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/locations';
};

export type GetApiUserLocationsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only authenticated users can access this resource
     */
    403: unknown;
    /**
     * Not Found: User not found
     */
    404: unknown;
};

export type GetApiUserLocationsResponses = {
    /**
     * OK
     */
    200: Array<UserEventLocationResponseDto>;
};

export type GetApiUserLocationsResponse = GetApiUserLocationsResponses[keyof GetApiUserLocationsResponses];

export type PostApiUserResendEmailConfirmationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/resend-email-confirmation';
};

export type PostApiUserResendEmailConfirmationErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: User not authenticated
     */
    403: unknown;
    /**
     * Not Found: User not found
     */
    404: unknown;
    /**
     * Internal Server Error: Error sending email
     */
    500: unknown;
};

export type PostApiUserResendEmailConfirmationResponses = {
    /**
     * Email confirmation resent successfully
     */
    204: void;
};

export type PostApiUserResendEmailConfirmationResponse = PostApiUserResendEmailConfirmationResponses[keyof PostApiUserResendEmailConfirmationResponses];

export type DeleteApiUserReservationsData = {
    body?: never;
    path?: never;
    query?: {
        ids?: Array<string>;
    };
    url: '/api/user/reservations';
};

export type DeleteApiUserReservationsErrors = {
    /**
     * Bad Request: Invalid input
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: User not authorized to delete reservation
     */
    403: unknown;
    /**
     * Not Found: Reservation with specified ID not found
     */
    404: unknown;
    /**
     * Internal Server Error: Database persistence error
     */
    500: unknown;
};

export type DeleteApiUserReservationsResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiUserReservationsResponse = DeleteApiUserReservationsResponses[keyof DeleteApiUserReservationsResponses];

export type GetApiUserReservationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/reservations';
};

export type GetApiUserReservationsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only authenticated users can access this resource
     */
    403: unknown;
};

export type GetApiUserReservationsResponses = {
    /**
     * OK
     */
    200: Array<UserReservationResponseDto>;
};

export type GetApiUserReservationsResponse = GetApiUserReservationsResponses[keyof GetApiUserReservationsResponses];

export type PostApiUserReservationsData = {
    body: UserReservationsRequestDto;
    path?: never;
    query?: never;
    url: '/api/user/reservations';
};

export type PostApiUserReservationsErrors = {
    /**
     * Bad Request: Invalid input or event not bookable or reservation limit reached or user email not verified
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only authenticated users can access this resource
     */
    403: unknown;
    /**
     * Not Found: Event or seat not found
     */
    404: unknown;
    /**
     * Conflict: Seat already reserved or blocked
     */
    409: unknown;
};

export type PostApiUserReservationsResponses = {
    /**
     * OK
     */
    200: Array<UserReservationResponseDto>;
};

export type PostApiUserReservationsResponse = PostApiUserReservationsResponses[keyof PostApiUserReservationsResponses];

export type GetApiUserReservationsByIdData = {
    body?: never;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/user/reservations/{id}';
};

export type GetApiUserReservationsByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only authenticated users can access this resource
     */
    403: unknown;
    /**
     * Not Found: Reservation with specified ID not found for the current user
     */
    404: unknown;
};

export type GetApiUserReservationsByIdResponses = {
    /**
     * OK
     */
    200: UserReservationResponseDto;
};

export type GetApiUserReservationsByIdResponse = GetApiUserReservationsByIdResponses[keyof GetApiUserReservationsByIdResponses];

export type PostApiUserVerifyEmailCodeData = {
    body: VerifyEmailCodeRequestDto;
    path?: never;
    query?: never;
    url: '/api/user/verify-email-code';
};

export type PostApiUserVerifyEmailCodeErrors = {
    /**
     * Bad Request: Invalid verification code format or code not found
     */
    400: unknown;
    /**
     * Gone: Verification code expired
     */
    410: unknown;
};

export type PostApiUserVerifyEmailCodeResponses = {
    /**
     * Email verified successfully
     */
    200: unknown;
};

export type GetApiUsersAdminData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/admin';
};

export type GetApiUsersAdminErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only ADMIN role can access this resource
     */
    403: unknown;
};

export type GetApiUsersAdminResponses = {
    /**
     * List of users (admin view) retrieved successfully
     */
    200: Array<UserDto>;
};

export type GetApiUsersAdminResponse = GetApiUsersAdminResponses[keyof GetApiUsersAdminResponses];

export type PostApiUsersAdminData = {
    body: AdminUserCreationDto;
    path?: never;
    query?: never;
    url: '/api/users/admin';
};

export type PostApiUsersAdminErrors = {
    /**
     * Bad Request: Invalid user data
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only ADMIN role can access this resource
     */
    403: unknown;
    /**
     * Conflict: User with this username already exists
     */
    409: unknown;
};

export type PostApiUsersAdminResponses = {
    /**
     * User created successfully
     */
    201: unknown;
};

export type PostApiUsersAdminImportData = {
    body: Array<AdminUserCreationDto>;
    path?: never;
    query?: never;
    url: '/api/users/admin/import';
};

export type PostApiUsersAdminImportErrors = {
    /**
     * Bad Request: Invalid user data
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only ADMIN role can access this resource
     */
    403: unknown;
    /**
     * Conflict: One or more users in the batch have a conflicting username or email
     */
    409: unknown;
};

export type PostApiUsersAdminImportResponses = {
    /**
     * Users imported successfully
     */
    200: Array<UserDto>;
};

export type PostApiUsersAdminImportResponse = PostApiUsersAdminImportResponses[keyof PostApiUsersAdminImportResponses];

export type DeleteApiUsersAdminByIdData = {
    body?: never;
    path?: never;
    query?: {
        ids?: Array<string>;
    };
    url: '/api/users/admin/{id}';
};

export type DeleteApiUsersAdminByIdErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only ADMIN role can access this resource
     */
    403: unknown;
    /**
     * Not Found: User with specified ID not found
     */
    404: unknown;
};

export type DeleteApiUsersAdminByIdResponses = {
    /**
     * User deleted successfully
     */
    204: void;
};

export type DeleteApiUsersAdminByIdResponse = DeleteApiUsersAdminByIdResponses[keyof DeleteApiUsersAdminByIdResponses];

export type PutApiUsersAdminByIdData = {
    body: AdminUserUpdateDto;
    path: {
        id: Uuid;
    };
    query?: never;
    url: '/api/users/admin/{id}';
};

export type PutApiUsersAdminByIdErrors = {
    /**
     * Bad Request: Invalid user data
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only ADMIN role can access this resource
     */
    403: unknown;
    /**
     * Not Found: User with specified ID not found
     */
    404: unknown;
    /**
     * Conflict: User with this username already exists
     */
    409: unknown;
    /**
     * Internal Server Error: Error sending email confirmation
     */
    500: unknown;
};

export type PutApiUsersAdminByIdResponses = {
    /**
     * User updated successfully
     */
    200: UserDto;
};

export type PutApiUsersAdminByIdResponse = PutApiUsersAdminByIdResponses[keyof PutApiUsersAdminByIdResponses];

export type GetApiUsersManagerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/manager';
};

export type GetApiUsersManagerErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only ADMIN or MANAGER roles can access this resource
     */
    403: unknown;
};

export type GetApiUsersManagerResponses = {
    /**
     * List of users (limited info) retrieved successfully
     */
    200: Array<LimitedUserInfoDto>;
};

export type GetApiUsersManagerResponse = GetApiUsersManagerResponses[keyof GetApiUsersManagerResponses];

export type GetApiUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type GetApiUsersMeErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only authenticated users can access this resource
     */
    403: unknown;
};

export type GetApiUsersMeResponses = {
    /**
     * Current user profile retrieved successfully
     */
    200: UserDto;
};

export type GetApiUsersMeResponse = GetApiUsersMeResponses[keyof GetApiUsersMeResponses];

export type PutApiUsersMeData = {
    body: UserProfileUpdateDto;
    path?: never;
    query?: never;
    url: '/api/users/me';
};

export type PutApiUsersMeErrors = {
    /**
     * Bad Request: Invalid user data
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only authenticated users can access this resource
     */
    403: unknown;
    /**
     * Not Found: User not found
     */
    404: unknown;
    /**
     * Conflict: User with this username already exists
     */
    409: unknown;
    /**
     * Internal Server Error: Error sending email confirmation
     */
    500: unknown;
};

export type PutApiUsersMeResponses = {
    /**
     * User profile updated successfully
     */
    200: UserDto;
};

export type PutApiUsersMeResponse = PutApiUsersMeResponses[keyof PutApiUsersMeResponses];

export type GetApiUsersRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/roles';
};

export type GetApiUsersRolesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden: Only authenticated users can access this resource
     */
    403: unknown;
};

export type GetApiUsersRolesResponses = {
    /**
     * List of available roles retrieved successfully
     */
    200: Array<string>;
};

export type GetApiUsersRolesResponse = GetApiUsersRolesResponses[keyof GetApiUsersRolesResponses];
