-- Baseline: the schema as it existed before UUID primary keys were introduced (bigint/bigserial
-- ids, generated by Hibernate via one distinct sequence per table). This mirrors exactly what
-- Hibernate's own `schema-management.strategy: update` had built up to this point.
--
-- This file exists so that a fresh, empty database replays the real schema history end-to-end
-- (V1 creates the old bigint schema, V2 migrates it to UUID) instead of jumping straight to the
-- target state. It is NOT meant to run against an already-existing production database: there,
-- Flyway is configured with baseline-on-migrate/baseline-version=1, so the database is simply
-- marked as "already at V1" without executing this script, and only V2 onward actually runs.

CREATE TABLE email_seat_map_token_seats (
    token_id bigint NOT NULL,
    seat_number character varying(255)
);

CREATE TABLE email_seat_map_tokens (
    created_at timestamp(6) with time zone NOT NULL,
    event_id bigint NOT NULL,
    expiration_time timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token character varying(64) NOT NULL
);

CREATE SEQUENCE email_seat_map_tokens_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE email_verification (
    expiration_time timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint,
    token character varying(255) NOT NULL
);

CREATE SEQUENCE email_verification_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE event_location_area_boundary (
    sort_order integer NOT NULL,
    xcoordinate integer,
    ycoordinate integer,
    area_id bigint NOT NULL,
    CONSTRAINT event_location_area_boundary_sort_order_check CHECK ((sort_order >= 0))
);

CREATE TABLE event_location_areas (
    event_location_id bigint,
    id bigint NOT NULL,
    name character varying(255)
);

CREATE SEQUENCE event_location_areas_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE event_location_entrances (
    event_location_id bigint,
    id bigint NOT NULL,
    name character varying(255)
);

CREATE SEQUENCE event_location_entrances_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE event_location_markers (
    xcoordinate integer,
    ycoordinate integer,
    event_location_id bigint,
    id bigint NOT NULL,
    label character varying(255)
);

CREATE SEQUENCE event_location_markers_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE event_supervisors (
    event_id bigint NOT NULL,
    user_id bigint NOT NULL
);

CREATE TABLE eventlocations (
    capacity integer,
    id bigint NOT NULL,
    manager_id bigint,
    address character varying(255),
    name character varying(255)
);

CREATE SEQUENCE eventlocations_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE events (
    remindersent boolean NOT NULL,
    bookingdeadline timestamp(6) with time zone,
    bookingstarttime timestamp(6) with time zone,
    endtime timestamp(6) with time zone,
    event_location_id bigint,
    id bigint NOT NULL,
    manager_id bigint,
    remindersenddate timestamp(6) with time zone,
    starttime timestamp(6) with time zone,
    description character varying(255),
    name character varying(255)
);

CREATE SEQUENCE events_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE eventuserallowance (
    reservationsallowedcount integer DEFAULT 1 NOT NULL,
    event_id bigint,
    id bigint NOT NULL,
    user_id bigint
);

CREATE SEQUENCE eventuserallowance_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE login_attempts (
    successful boolean NOT NULL,
    attempttime timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint,
    username character varying(255) NOT NULL
);

CREATE SEQUENCE login_attempts_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE outbound_email_attachments (
    email_id bigint NOT NULL,
    id bigint NOT NULL,
    content_id character varying(255),
    content_type character varying(255) NOT NULL,
    file_name character varying(255) NOT NULL,
    data oid NOT NULL
);

CREATE SEQUENCE outbound_email_attachments_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE outbound_email_bcc (
    email_id bigint NOT NULL,
    address character varying(255) NOT NULL
);

CREATE TABLE outbound_email_cc (
    email_id bigint NOT NULL,
    address character varying(255) NOT NULL
);

CREATE TABLE outbound_email_recipients (
    email_id bigint NOT NULL,
    address character varying(255) NOT NULL
);

CREATE TABLE outbound_emails (
    attempts integer NOT NULL,
    max_attempts integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    next_attempt_at timestamp(6) with time zone NOT NULL,
    sent_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone NOT NULL,
    status character varying(16) NOT NULL,
    subject character varying(1024) NOT NULL,
    last_error character varying(2048),
    html_body oid NOT NULL,
    CONSTRAINT outbound_emails_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SENDING'::character varying, 'SENT'::character varying, 'FAILED'::character varying])::text[])))
);

CREATE SEQUENCE outbound_emails_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE refresh_tokens (
    createdat timestamp(6) with time zone,
    expiresat timestamp(6) with time zone,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    tokenhash character varying(255)
);

CREATE SEQUENCE refresh_tokens_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE reservations (
    event_id bigint,
    id bigint NOT NULL,
    reservationdate timestamp(6) with time zone,
    seat_id bigint,
    user_id bigint,
    checkincode character varying(255),
    livestatus character varying(255),
    status character varying(255),
    CONSTRAINT reservations_livestatus_check CHECK (((livestatus)::text = ANY ((ARRAY['CHECKED_IN'::character varying, 'CANCELLED'::character varying, 'NO_SHOW'::character varying])::text[]))),
    CONSTRAINT reservations_status_check CHECK (((status)::text = ANY ((ARRAY['RESERVED'::character varying, 'BLOCKED'::character varying])::text[])))
);

CREATE SEQUENCE reservations_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE seats (
    xcoordinate integer,
    ycoordinate integer,
    area_id bigint,
    entrance_id bigint,
    id bigint NOT NULL,
    location_id bigint,
    seatnumber character varying(255) NOT NULL,
    seatrow character varying(255)
);

CREATE SEQUENCE seats_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE user_roles (
    user_id bigint NOT NULL,
    role character varying(255)
);

CREATE TABLE user_tags (
    user_id bigint NOT NULL,
    tags character varying(255)
);

CREATE TABLE users (
    emailverificationsent boolean,
    emailverified boolean,
    id bigint NOT NULL,
    email character varying(255),
    firstname character varying(255),
    lastname character varying(255),
    passwordhash character varying(255),
    passwordsalt character varying(255),
    username character varying(255) NOT NULL
);

CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE TABLE webauthn_credentials (
    counter bigint NOT NULL,
    createdat timestamp(6) with time zone,
    id bigint NOT NULL,
    lastusedat timestamp(6) with time zone,
    publickeyalgorithm bigint NOT NULL,
    user_id bigint NOT NULL,
    aaguid uuid,
    credentialid character varying(1024) NOT NULL,
    label character varying(255),
    publickey bytea NOT NULL
);

CREATE SEQUENCE webauthn_credentials_seq START WITH 1 INCREMENT BY 50 NO MINVALUE NO MAXVALUE CACHE 1;

ALTER TABLE ONLY email_seat_map_token_seats ADD CONSTRAINT email_seat_map_token_seats_token_id_seat_number_key UNIQUE (token_id, seat_number);
ALTER TABLE ONLY email_seat_map_tokens ADD CONSTRAINT email_seat_map_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY email_seat_map_tokens ADD CONSTRAINT email_seat_map_tokens_token_key UNIQUE (token);
ALTER TABLE ONLY email_verification ADD CONSTRAINT email_verification_pkey PRIMARY KEY (id);
ALTER TABLE ONLY email_verification ADD CONSTRAINT email_verification_token_key UNIQUE (token);
ALTER TABLE ONLY email_verification ADD CONSTRAINT email_verification_user_id_key UNIQUE (user_id);
ALTER TABLE ONLY event_location_area_boundary ADD CONSTRAINT event_location_area_boundary_pkey PRIMARY KEY (sort_order, area_id);
ALTER TABLE ONLY event_location_areas ADD CONSTRAINT event_location_areas_pkey PRIMARY KEY (id);
ALTER TABLE ONLY event_location_entrances ADD CONSTRAINT event_location_entrances_pkey PRIMARY KEY (id);
ALTER TABLE ONLY event_location_markers ADD CONSTRAINT event_location_markers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY event_supervisors ADD CONSTRAINT event_supervisors_pkey PRIMARY KEY (event_id, user_id);
ALTER TABLE ONLY eventlocations ADD CONSTRAINT eventlocations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY events ADD CONSTRAINT events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY eventuserallowance ADD CONSTRAINT eventuserallowance_pkey PRIMARY KEY (id);
ALTER TABLE ONLY login_attempts ADD CONSTRAINT login_attempts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY outbound_email_attachments ADD CONSTRAINT outbound_email_attachments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY outbound_emails ADD CONSTRAINT outbound_emails_pkey PRIMARY KEY (id);
ALTER TABLE ONLY refresh_tokens ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY reservations ADD CONSTRAINT reservations_event_id_seat_id_key UNIQUE (event_id, seat_id);
ALTER TABLE ONLY reservations ADD CONSTRAINT reservations_event_id_user_id_checkincode_key UNIQUE (event_id, user_id, checkincode);
ALTER TABLE ONLY reservations ADD CONSTRAINT reservations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY seats ADD CONSTRAINT seats_pkey PRIMARY KEY (id);
ALTER TABLE ONLY seats ADD CONSTRAINT seats_seatnumber_location_id_key UNIQUE (seatnumber, location_id);
ALTER TABLE ONLY user_roles ADD CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id, role);
ALTER TABLE ONLY user_tags ADD CONSTRAINT user_tags_user_id_tags_key UNIQUE (user_id, tags);
ALTER TABLE ONLY users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY users ADD CONSTRAINT users_username_key UNIQUE (username);
ALTER TABLE ONLY webauthn_credentials ADD CONSTRAINT webauthn_credentials_credentialid_key UNIQUE (credentialid);
ALTER TABLE ONLY webauthn_credentials ADD CONSTRAINT webauthn_credentials_pkey PRIMARY KEY (id);

CREATE INDEX idx_expiration_time ON email_seat_map_tokens USING btree (expiration_time);
CREATE INDEX idx_outbound_email_next_attempt ON outbound_emails USING btree (next_attempt_at);
CREATE INDEX idx_outbound_email_status ON outbound_emails USING btree (status);
CREATE INDEX idx_token ON email_seat_map_tokens USING btree (token);
CREATE INDEX idx_user_event ON email_seat_map_tokens USING btree (user_id, event_id);

ALTER TABLE ONLY refresh_tokens ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE ONLY event_supervisors ADD CONSTRAINT fk3aoscdyd7pr6u826dxmj5eq34 FOREIGN KEY (event_id) REFERENCES events(id);
ALTER TABLE ONLY event_location_markers ADD CONSTRAINT fk3svetled00reig5xnq9t4uucj FOREIGN KEY (event_location_id) REFERENCES eventlocations(id);
ALTER TABLE ONLY events ADD CONSTRAINT fk4lsvuu8y3xvo76gd0q1u30nnj FOREIGN KEY (manager_id) REFERENCES users(id);
ALTER TABLE ONLY reservations ADD CONSTRAINT fk57amums6j9fkqwbpw4oceyw9i FOREIGN KEY (seat_id) REFERENCES seats(id);
ALTER TABLE ONLY event_location_entrances ADD CONSTRAINT fk5d8980bb9w8gflo6kuaulslmc FOREIGN KEY (event_location_id) REFERENCES eventlocations(id);
ALTER TABLE ONLY eventuserallowance ADD CONSTRAINT fk5xruwwuqkxk5ufwpe5456qu84 FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE ONLY webauthn_credentials ADD CONSTRAINT fk61k8kijke2qqqpsrg65qjwcie FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE ONLY eventuserallowance ADD CONSTRAINT fk7jrv62d8lhjl3a20qv7dupmcc FOREIGN KEY (event_id) REFERENCES events(id);
ALTER TABLE ONLY outbound_email_cc ADD CONSTRAINT fk9iqj75se6yd752rpnvh444t2y FOREIGN KEY (email_id) REFERENCES outbound_emails(id);
ALTER TABLE ONLY reservations ADD CONSTRAINT fkb5g9io5h54iwl2inkno50ppln FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE ONLY email_verification ADD CONSTRAINT fkbh3863tiicveqq2k27uooni0g FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE ONLY reservations ADD CONSTRAINT fkcnr8finplwp8whntrr02jpvre FOREIGN KEY (event_id) REFERENCES events(id);
ALTER TABLE ONLY user_tags ADD CONSTRAINT fkdylhtw3qjb2nj40xp50b0p495 FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE ONLY seats ADD CONSTRAINT fkewopqcg6ejtw7w1cr72h81uic FOREIGN KEY (entrance_id) REFERENCES event_location_entrances(id);
ALTER TABLE ONLY event_location_area_boundary ADD CONSTRAINT fkfho28q7mc9mn6ku9vaah1ecad FOREIGN KEY (area_id) REFERENCES event_location_areas(id);
ALTER TABLE ONLY event_supervisors ADD CONSTRAINT fkh5dc0cko6fxnrh14ab4u9hgsq FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE ONLY events ADD CONSTRAINT fkhbmiaeypek6v8lya3ekrbim3l FOREIGN KEY (event_location_id) REFERENCES eventlocations(id);
ALTER TABLE ONLY user_roles ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE ONLY email_seat_map_tokens ADD CONSTRAINT fki7ok9vlqtnek7sfpejikoppbm FOREIGN KEY (event_id) REFERENCES events(id);
ALTER TABLE ONLY eventlocations ADD CONSTRAINT fkjyf4c2l9fjuhk4lfjtd1nc813 FOREIGN KEY (manager_id) REFERENCES users(id);
ALTER TABLE ONLY outbound_email_bcc ADD CONSTRAINT fkkbqiu53cwbwt37ius2rmdgrn3 FOREIGN KEY (email_id) REFERENCES outbound_emails(id);
ALTER TABLE ONLY outbound_email_attachments ADD CONSTRAINT fkodwuh62l6gv1jsvllvodtwwwn FOREIGN KEY (email_id) REFERENCES outbound_emails(id);
ALTER TABLE ONLY outbound_email_recipients ADD CONSTRAINT fkoia5cdiai43feapmxw3fh7aqn FOREIGN KEY (email_id) REFERENCES outbound_emails(id);
ALTER TABLE ONLY email_seat_map_tokens ADD CONSTRAINT fkomqn7ooasx3jq8oo2hs3lw2vf FOREIGN KEY (user_id) REFERENCES users(id);
ALTER TABLE ONLY email_seat_map_token_seats ADD CONSTRAINT fkpywj3cn0csx3jpr0sneprc7wo FOREIGN KEY (token_id) REFERENCES email_seat_map_tokens(id);
ALTER TABLE ONLY seats ADD CONSTRAINT fkqghl2hgr3uhl9krv29b4xeqcq FOREIGN KEY (area_id) REFERENCES event_location_areas(id);
ALTER TABLE ONLY event_location_areas ADD CONSTRAINT fkscw524e3yojfvg7ed2chgccxr FOREIGN KEY (event_location_id) REFERENCES eventlocations(id);
ALTER TABLE ONLY seats ADD CONSTRAINT fktbc2ac345o9925k9xgxxchgkm FOREIGN KEY (location_id) REFERENCES eventlocations(id);
ALTER TABLE ONLY login_attempts ADD CONSTRAINT fktg9vhke4mlf5vij2rcvfk2dg2 FOREIGN KEY (user_id) REFERENCES users(id);
