name: build.yml
on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "**/*.md" ]
    tags:
      - "v*.*"
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "**/*.md" ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write


jobs:
  frontend:
    uses: ./.github/workflows/frontend.yml
    with:
      enable-docker-build: true

  maven:
    needs: frontend
    uses: ./.github/workflows/maven.yml
    with:
      build-artifact-name: quarkus-app
      build-artifact-path: target/quarkus-app

  backend-docker:
    needs: maven
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: ./.github/workflows/docker.yml
    with:
      build-artifact-name: quarkus-app
      build-artifact-path: target/quarkus-app
      docker-file-path: ./src/main/docker/Dockerfile.jvm
      container-image-title: Backend

  frontend-docker:
    needs: frontend
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: ./.github/workflows/docker.yml
    with:
      build-artifact-name: frontend-build
      build-artifact-path: webapp/out
      docker-file-path: ./webapp/Dockerfile
      container-image-title: Frontend
      image-name: ${{ github.repository }}-frontend