name: native-build.yml
on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "**/*.md" ]
    tags:
      - "v*.*"
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "**/*.md" ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  frontend:
    uses: ./.github/workflows/frontend.yml

  maven-native:
    needs: frontend
    uses: ./.github/workflows/maven.yml
    with:
      maven-args: "-Pnative"
      build-artifact-name: quarkus-app-native
      build-artifact-path: target/*-runner

  docker-native:
    needs: maven-native
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: ./.github/workflows/docker.yml
    with:
      build-artifact-name: quarkus-app-native
      build-artifact-path: target
      docker-file-path: ./src/main/docker/Dockerfile.native
      container-image-title: Backend-Native
      image-name: ${{ github.repository }}-native