name: vite.yml
on:
  workflow_call:

jobs:
  vite:
    name: vite build
    runs-on: "ubuntu-24.04"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Maven Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: List the state of node modules
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: |
              cd webapp
              npm list

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
              cd webapp
              npm ci

      - name: Run generate:api
        run: |
              cd webapp 
              npm run generate:api

      - name: Check for changes of api client
        run: git diff --exit-code -- webapp/src/api/

      - name: Run ESLint
        run: |
              cd webapp
              npm run lint:check

      - name: Run Prettier
        run: |
              cd webapp
              npm run format:check

      - name: Build
        run: |
              cd webapp
              npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite-dist
          path: webapp/dist